#!/usr/bin/env bash
# Issue a free, true wildcard TLS cert for *.provisa.dev and wire it into terraform.
#
# Cheapest provider: Let's Encrypt (free, trusted, 90-day). Wildcard issuance requires
# the DNS-01 challenge, solved here against Cloudflare (the zone provisa.dev lives on).
# One cert covers cloud.provisa.dev and every {org}.provisa.dev across all protocols
# (REQ-1233/1239/1240). Renew by re-running this script (Let's Encrypt certs are 90-day).
#
# Prerequisites:
#   - ACME_EMAIL                 contact email for the ACME account
#   - CLOUDFLARE_DNS_API_TOKEN   Cloudflare token scoped Zone.DNS:Edit on provisa.dev only
#   - lego on PATH (auto-installed via Homebrew if missing)
#
# Usage:
#   ACME_EMAIL=you@example.com CLOUDFLARE_DNS_API_TOKEN=xxxx ./issue-wildcard-cert.sh
#
# On success it writes terraform/gcp/certs.auto.tfvars (git-ignored) setting
# tls_cert_pem / tls_key_pem, so the next `terraform apply` serves the real cert.
set -euo pipefail

DOMAIN="${DOMAIN:-provisa.dev}"
: "${ACME_EMAIL:?set ACME_EMAIL to your ACME contact email}"
: "${CLOUDFLARE_DNS_API_TOKEN:?set CLOUDFLARE_DNS_API_TOKEN (Cloudflare token, Zone.DNS:Edit on ${DOMAIN})}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_DIR="${OUT_DIR:-${HOME}/.provisa/certs/${DOMAIN}}"
TFVARS="${TF_DIR}/certs.auto.tfvars"

# Let's Encrypt staging (untrusted) for dry runs: STAGING=1. Production is the default.
if [ "${STAGING:-0}" = "1" ]; then
  ACME_SERVER="https://acme-staging-v02.api.letsencrypt.org/directory"
  echo "[issue-wildcard-cert] STAGING — issuing an UNTRUSTED cert (dry run)."
else
  ACME_SERVER="https://acme-v02.api.letsencrypt.org/directory"
fi

if ! command -v lego >/dev/null 2>&1; then
  if command -v brew >/dev/null 2>&1; then
    echo "[issue-wildcard-cert] lego not found — installing via Homebrew."
    brew install lego
  else
    echo "[issue-wildcard-cert] lego not found and Homebrew unavailable." >&2
    echo "Install lego from https://github.com/go-acme/lego/releases and re-run." >&2
    exit 1
  fi
fi

mkdir -p "${OUT_DIR}"

# lego 5.x: challenge/account flags belong to the `run` subcommand, not the globals.
# --domains order matters: the first is the cert's common file name. Wildcard first so
# the output lands at _.${DOMAIN}.{crt,key}; apex added as a SAN.
# --dns.resolvers: check propagation against public resolvers, NOT the machine's default
# recursive resolver (a home router at 192.168.x.1 negatively-caches _acme-challenge and
# returns NXDOMAIN for the full 2m timeout even after Cloudflare has the TXT record).
CLOUDFLARE_DNS_API_TOKEN="${CLOUDFLARE_DNS_API_TOKEN}" \
lego run \
  --path "${OUT_DIR}" \
  --accept-tos \
  --email "${ACME_EMAIL}" \
  --server "${ACME_SERVER}" \
  --dns cloudflare \
  --dns.resolvers "1.1.1.1:53" \
  --dns.resolvers "8.8.8.8:53" \
  --domains "*.${DOMAIN}" \
  --domains "${DOMAIN}"

CRT="${OUT_DIR}/certificates/_.${DOMAIN}.crt"
KEY="${OUT_DIR}/certificates/_.${DOMAIN}.key"

if [ ! -f "${CRT}" ] || [ ! -f "${KEY}" ]; then
  echo "[issue-wildcard-cert] expected cert files not found:" >&2
  echo "  ${CRT}" >&2
  echo "  ${KEY}" >&2
  exit 1
fi

# lego's .crt is already the full chain (leaf + issuer). Emit HCL heredocs so terraform
# reads the PEM verbatim.
umask 077
{
  echo "# Generated by scripts/issue-wildcard-cert.sh — wildcard *.${DOMAIN} (Let's Encrypt)."
  echo "# Contains a private key. Never commit. Re-run the script to renew (90-day certs)."
  echo "tls_cert_pem = <<-CERT"
  cat "${CRT}"
  echo "CERT"
  echo ""
  echo "tls_key_pem = <<-KEY"
  cat "${KEY}"
  echo "KEY"
} > "${TFVARS}"

echo ""
echo "[issue-wildcard-cert] wildcard cert issued:"
echo "  cert: ${CRT}"
echo "  key:  ${KEY}"
echo "[issue-wildcard-cert] terraform vars written: ${TFVARS}"
echo "[issue-wildcard-cert] next: cd ${TF_DIR} && terraform apply"
echo "[issue-wildcard-cert] then point Cloudflare DNS (grey-cloud / DNS-only):"
echo "    cloud.${DOMAIN}  A  -> UI LB IP"
echo "    *.${DOMAIN}      A  -> API/data LB IP"
