# Copyright (c) 2026 Kenneth Stott
# Canary: 95f3b0ff-18b6-4374-8505-e2dff9e8018c
#
# This source code is licensed under the Business Source License 1.1
# found in the LICENSE file in the root directory of this source tree.
#
# NOTICE: Use of this software for training artificial intelligence or
# machine learning models is strictly prohibited without explicit written
# permission from the copyright holder.

"""Dependence kept in generation (REQ-1939, DEPENDENCE KEPT; maintainer ruling Y1).

A profile run measures each pair of a table's columns' rank correlation (Spearman, a category
entering as the middle of its share's slice of 0 to 1, in value order) and a dependency network
-- for a column, the one or two columns its values depend on most -- with the joint counts of
their states (a category's value, a number's decile of rank) (provisa.profiler.dependence).

Generation keeps both:

* the columns that enter the COPULA -- a number drawn through its sketch, a category drawn by
  its shares (a declared categories or bool fake, or an undeclared column of few values), and a
  declared distribution or profile() fake -- take their uniform point jointly: independent
  normals, mixed by the Cholesky factor of the Pearson matrix the Spearman matrix implies
  (``2 sin(πρ/6)``), each mapped back through the normal CDF, so each column keeps its own
  distribution and the pairs keep their rank correlation;
* a column the network ties to others is drawn after them: its state from the joint counts given
  its parents' generated states, its value from that state -- a category's value, a number's
  decile of its own sketch.

Methods, pattern(), hash() and relative fakes keep their own draws; the report names them.
"""

# Requirements: REQ-1939

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class Parent:
    """A network parent: one of the table's columns, or a parent table's -- reached through the
    table's column ``via`` that refers to it, and drawable only where that is the relationship
    the table's rows are generated by."""

    column: str  # registered (physical) name, in its own table
    via: str | None = None  # the child's referring column, for a parent table's column


@dataclass(frozen=True)
class Joint:
    """One joint count: the target's state and its parents' states, each a category's value
    (text) or a number's decile of rank (int)."""

    target: str | int
    parents: tuple[str | int, ...]
    count: int


@dataclass(frozen=True)
class Dependence:
    """What a profile run measured of a table's dependence, by registered column name."""

    spearman: dict[tuple[str, str], float] = field(default_factory=dict)
    network: dict[str, tuple[Parent, ...]] = field(default_factory=dict)
    joints: dict[str, tuple[Joint, ...]] = field(default_factory=dict)
    unreached: frozenset[str] = frozenset()  # network columns whose parents generation cannot reach


def pearson(rho_s: float) -> float:
    """The normal copula's correlation that gives rank correlation ``rho_s``."""
    return 2.0 * math.sin(math.pi * rho_s / 6.0)


def _factor(m: list[list[float]]) -> list[list[float]] | None:
    """The lower Cholesky factor of ``m``, or None where it is not positive definite."""
    n = len(m)
    low = [[0.0] * n for _ in range(n)]
    for i in range(n):
        for j in range(i + 1):
            s = sum(low[i][k] * low[j][k] for k in range(j))
            if i == j:
                d = m[i][i] - s
                if d <= 1e-9:
                    return None
                low[i][j] = math.sqrt(d)
            else:
                low[i][j] = (m[i][j] - s) / low[j][j]
    return low


def _shrunk(matrix: list[list[float]], shrink: float) -> list[list[float]]:
    n = len(matrix)
    return [[1.0 if i == j else (1 - shrink) * matrix[i][j] for j in range(n)] for i in range(n)]


def cholesky(matrix: list[list[float]]) -> tuple[list[list[float]], float]:
    """The lower Cholesky factor of a correlation matrix, and the shrink toward independence it
    took. REQ-1939, DEPENDENCE KEPT: pairs measured one at a time need not agree as a whole, and
    a matrix that is not positive definite cannot be drawn from; the smallest shrink that makes
    it so -- found by bisection to 1e-6 -- is applied, and the report states it beside the
    measured and generated correlations, so its effect is seen."""
    low = _factor(matrix)
    if low is not None:
        return low, 0.0
    lo, hi = 0.0, 1.0  # the identity (shrink 1) always factors
    for _ in range(20):
        mid = (lo + hi) / 2
        if _factor(_shrunk(matrix, mid)) is None:
            lo = mid
        else:
            hi = mid
    low = _factor(_shrunk(matrix, hi))
    assert low is not None  # hi is a shrink that factored, or the identity
    return low, hi


def copula_factor(
    columns: list[str], spearman: dict[tuple[str, str], float]
) -> tuple[list[list[float]], float]:
    """The Cholesky factor mixing the columns' normals, from their measured rank correlations
    (a pair not measured is independent), and the shrink its repair took (:func:`cholesky`)."""
    n = len(columns)
    m = [[1.0 if i == j else 0.0 for j in range(n)] for i in range(n)]
    for i, a in enumerate(columns):
        for j, b in enumerate(columns):
            if i < j:
                rho = spearman.get((a, b), spearman.get((b, a)))
                if rho is not None:
                    m[i][j] = m[j][i] = pearson(rho)
    return cholesky(m)


def normal_cdf_sql(x: str) -> str:
    """Φ(x) in the governed dialect: Abramowitz and Stegun 26.2.17 (absolute error < 7.5e-8),
    with no engine's own erf (Trino and DuckDB have none)."""
    t = f"(1.0 / (1.0 + 0.2316419 * ABS({x})))"
    poly = (
        f"({t} * (0.319381530 + {t} * (-0.356563782 + {t} * (1.781477937 + {t} * "
        f"(-1.821255978 + {t} * 1.330274429)))))"
    )
    tail = f"(0.3989422804014327 * EXP(-0.5 * {x} * {x}) * {poly})"
    return f"(CASE WHEN {x} >= 0 THEN 1.0 - {tail} ELSE {tail} END)"


def conditional(
    joints: tuple[Joint, ...],
) -> tuple[
    dict[tuple[str | int, ...], list[tuple[str | int, float]]], list[tuple[str | int, float]]
]:
    """The target's states given each parents' combination, as shares; and its marginal shares,
    drawn where a combination was never seen."""
    by: dict[tuple[str | int, ...], dict[str | int, int]] = {}
    marginal: dict[str | int, int] = {}
    for j in joints:
        by.setdefault(j.parents, {})
        by[j.parents][j.target] = by[j.parents].get(j.target, 0) + j.count
        marginal[j.target] = marginal.get(j.target, 0) + j.count

    def shares(counts: dict[str | int, int]) -> list[tuple[str | int, float]]:
        total = sum(counts.values())
        return [(s, n / total) for s, n in sorted(counts.items(), key=lambda kv: str(kv[0]))]

    return {k: shares(v) for k, v in by.items()}, shares(marginal)


# -- the plan ---------------------------------------------------------------------------------


@dataclass(frozen=True)
class Node:
    """A column dependence decides. ``kind`` number: its state is the decile of its uniform
    point; category: the value whose slice of 0 to 1 the point falls in, ``slices`` the values in
    order with each slice's start and width (the order the column's draw uses)."""

    name: str
    kind: str  # number | category
    slices: tuple[tuple[str | None, float, float], ...] = ()
    own_salt: str = "value"  # the column's own uniform's salt, where neither copula nor network
    draw_key: bool = True  # whether its own uniform is drawn by the row (pool slots are not)


@dataclass(frozen=True)
class Target:
    """A column drawn from the joint counts given its parents' states. A parent is one of the
    table's nodes (by name) or a parent table's column read off the joined parent row
    (``("__parent__", column, deciles or None)``: deciles of its sketch for a number)."""

    name: str
    parents: tuple[Any, ...]
    given: dict[tuple[Any, ...], list[tuple[Any, float]]]
    marginal: list[tuple[Any, float]]


@dataclass(frozen=True)
class DependencePlan:
    nodes: dict[str, Node]
    copula: tuple[str, ...]
    factor: tuple[tuple[float, ...], ...]
    targets: tuple[Target, ...]  # in drawing order: every target after its parents
    kept_own: tuple[str, ...] = ()  # columns the run ties to others that keep their own draws
    shrink: float = 0.0  # the copula matrix's repair toward independence (cholesky)
