# Copyright (c) 2026 Kenneth Stott
# Canary: 3d8f1a27-6c94-4e0b-b2d5-a7e1c9f04b38
#
# This source code is licensed under the Business Source License 1.1
# found in the LICENSE file in the root directory of this source tree.
#
# NOTICE: Use of this software for training artificial intelligence or
# machine learning models is strictly prohibited without explicit written
# permission from the copyright holder.

"""The generation statement of one synthetic table (REQ-1939).

A synthetic table is generated by ONE SELECT the engine runs: nothing is read, every value is a
pure function of the dataset's seed, the table, the column and the row, so the same seed and scale
give the same rows on every run. Uniform draws are hashes of those inputs; each column maps its
uniforms through what its profile recorded:

* a key column takes the row number (offset into its profiled range), so it is unique;
* a foreign key of the table's driving relationship is its parent's key, the table's rows being
  generated parent by parent with a child count drawn from the relationship's profiled fan-out
  sketch, and the hot parents -- the most frequent keys of the child's column, beyond what the
  sketch resolves -- given their own scaled child counts, so join fan-out and its skew survive; another foreign key draws its parent
  uniformly over the parent's generated keys;
* a column declaring the categories fake draws the operator's listed values (REQ-1494), and a
  boolean its two values, by their frequencies;
* a column with a full value-frequency table and no fake keeps its number of distinct values and
  their shares on generated values;
* any other column draws through its 101-point quantile sketch (numeric, temporal) or its value
  shapes (text), never from its recorded most frequent values;
* a column whose distinct count does not grow with its rows draws from a fixed pool of that many
  values, so its vocabulary size is kept at any scale;
* null shares are kept, and an integer-only column stays integral.

The statement is written in the engine's dialect: DuckDB (the test stack's engine) and Trino.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from provisa.fakes.projection import DIGEST, layered, references
from provisa.synthetic.group import (
    GroupColumn,
    child_placeholder,
    group_levels,
    reads_children,
)

DIALECTS = ("duckdb", "trino")

_TWO_64 = "18446744073709551616.0"


@dataclass(frozen=True)
class ForeignKey:
    """A column drawing its value from a parent's generated keys."""

    parent_table: str
    parent_rows: int
    parent_key: "ColumnPlan"


@dataclass(frozen=True)
class ColumnPlan:
    name: str
    sql_type: str  # the engine type the value is cast to
    family: str  # numeric | temporal | text | boolean | other
    null_share: float = 0.0
    key: bool = False
    key_offset: int = 0  # an integer key starts here (its profiled minimum)
    key_shape: str | None = None  # a text key fills this shape with the row number
    foreign_key: ForeignKey | None = None
    driving: bool = False  # the foreign key of the relationship the rows are generated by
    frequencies: tuple[tuple[str | None, float], ...] = ()  # the whole vocabulary, by share
    sketch: tuple[float, ...] | None = None  # 101 points
    shapes: tuple[tuple[str, float], ...] = ()  # by share
    integer_only: bool = False
    pool: int | None = None  # a fixed vocabulary of this many values; None grows with rows
    # The shares of the pool's values, most frequent first: a skewed vocabulary keeps its skew on
    # generated values (empty: the pool's values are equally likely).
    pool_shares: tuple[float, ...] = ()
    # REQ-1494, REQ-1939: the column's synthetic rule, else its fake, computed over the generated
    # row as a faked read computes it (provisa.fakes.read_sql.Column); None for none.
    fake: Any = None
    # The row's value is only whether it is NULL (1, or NULL at the null share): the fake decides
    # every value and reads no generated value of its own column.
    marker: bool = False


@dataclass(frozen=True)
class PlannedCondition:
    """A conditional child count (REQ-1939, CONDITIONAL FAN-OUT): ``condition`` over the parent
    row, in the governed dialect, and the count a parent meeting it takes -- ``fixed``, a ``low``
    to ``high`` range drawn evenly, or a draw from ``sketch``, the fan-out measured for the real
    parents meeting it."""

    condition: str
    fixed: int | None = None
    low: int | None = None
    high: int | None = None
    sketch: tuple[float, ...] | None = None


@dataclass(frozen=True)
class TablePlan:
    name: str  # the table as the dataset names it (salts every draw)
    rows: int  # for a table generated row by row
    columns: tuple[ColumnPlan, ...]
    # The relationship the rows are generated by: (parent rows, the fan-out sketch, and the child
    # counts of its hot parents -- the first parents generated, one each -- beyond the sketch).
    fanout: tuple[int, tuple[float, ...], tuple[int, ...]] | None = None
    seed: int = 0
    notes: tuple[str, ...] = field(default=())
    # REQ-1494, REQ-1939: the row-spanning rules (provisa.synthetic.group), computed over the
    # generated rows; and the most children a parent has, where a sequence's entity is the
    # relationship the rows are generated by (no entity holds more rows than states).
    group: tuple[GroupColumn, ...] = ()
    cap: int | None = None
    # The relationship's conditional child counts, the parent's plan (whose rows the conditions
    # read, generated again inside this statement: the same rows, by the same seed) and the
    # parent's key column.
    conditions: tuple[PlannedCondition, ...] = ()
    parent: "TablePlan | None" = None
    parent_key: str | None = None


def _lit(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


class _Dialect:
    def __init__(self, name: str) -> None:
        if name not in DIALECTS:
            raise ValueError(
                f"no synthetic generation for engine dialect {name!r}; one of {DIALECTS}"
            )
        self.name = name

    def uniform(self, seed: int, table: str, column: str, salt: str, key: str) -> str:
        """A uniform draw in [0, 1) from the seed, table, column, a salt and the row key."""
        tag = _lit(f"{seed}:{table}:{column}:{salt}")
        if self.name == "duckdb":
            return f"(hash({tag}, {key}) / {_TWO_64})"
        return (
            f"(CAST(from_big_endian_64(xxhash64(to_utf8(concat({tag}, ':', CAST({key} AS varchar)))))"
            f" AS double) / {_TWO_64} + 0.5)"
        )

    def array(self, values: tuple[float, ...]) -> str:
        body = ", ".join(repr(float(v)) for v in values)
        return f"[{body}]" if self.name == "duckdb" else f"ARRAY[{body}]"

    def at(self, arr: str, index: str) -> str:
        """1-based element ``index`` of ``arr``."""
        return (
            f"list_extract({arr}, {index})"
            if self.name == "duckdb"
            else f"element_at({arr}, {index})"
        )

    def from_epoch(self, expr: str, sql_type: str) -> str:
        ts = f"to_timestamp({expr})" if self.name == "duckdb" else f"from_unixtime({expr})"
        return f"CAST({ts} AS {sql_type})"

    def fill_shape(self, shape: str, key: str, salt_seed: str) -> str:
        """``shape`` with each ``A``/``a``/``9`` replaced by a letter or digit drawn from ``key``."""
        pos = "_pos"
        if self.name == "duckdb":
            draw = f"hash({salt_seed}, {key}, {pos})"
            return (
                f"array_to_string(list_transform(range(length({_lit(shape)})), {pos} -> "
                f"CASE substr({_lit(shape)}, {pos} + 1, 1) "
                f"WHEN 'A' THEN chr(65 + CAST({draw} % 26 AS INTEGER)) "
                f"WHEN 'a' THEN chr(97 + CAST({draw} % 26 AS INTEGER)) "
                f"WHEN '9' THEN chr(48 + CAST({draw} % 10 AS INTEGER)) "
                f"ELSE substr({_lit(shape)}, {pos} + 1, 1) END), '')"
            )
        draw = (
            f"abs(from_big_endian_64(xxhash64(to_utf8(concat({salt_seed}, ':', "
            f"CAST({key} AS varchar), ':', CAST({pos} AS varchar))))))"
        )
        return (
            f"array_join(transform(sequence(1, length({_lit(shape)})), {pos} -> "
            f"CASE substr({_lit(shape)}, {pos}, 1) "
            f"WHEN 'A' THEN chr(65 + CAST({draw} % 26 AS integer)) "
            f"WHEN 'a' THEN chr(97 + CAST({draw} % 26 AS integer)) "
            f"WHEN '9' THEN chr(48 + CAST({draw} % 10 AS integer)) "
            f"ELSE substr({_lit(shape)}, {pos}, 1) END), '')"
        )

    def digest(self, seed: int, table: str, column: str, key: str) -> str:
        """A signed 64-bit draw from the seed, table, column and row key: the digest a fake
        computed in generation is seeded by, as a faked read's is by the real value (REQ-1939)."""
        tag = _lit(f"{seed}:{table}:{column}:fake")
        if self.name == "duckdb":
            return f"CAST(hash({tag}, {key}) >> 1 AS BIGINT)"
        return f"from_big_endian_64(xxhash64(to_utf8(concat({tag}, ':', CAST({key} AS varchar)))))"

    def lpad(self, expr: str, width: int) -> str:
        # Never truncated: a number longer than the shape's digits keeps every digit, so keys
        # filled into a shape stay unique at any row count.
        text = f"CAST({expr} AS varchar)"
        return (
            f"(CASE WHEN length({text}) >= {width} THEN {text} ELSE lpad({text}, {width}, '0') END)"
        )

    def value_digest(self, seed: int, table: str, column: str, value: str) -> str:
        """A signed 64-bit draw from the seed, table, column and a generated value: the digest
        of a fake that computes from the column's own value (bucket, truncate, prefix, hash), so
        one value gives one fake, as a faked read's digest of the real value does."""
        tag = _lit(f"{seed}:{table}:{column}:value")
        text = f"CAST({value} AS varchar)"
        if self.name == "duckdb":
            return f"CAST(hash({tag}, {text}) >> 1 AS BIGINT)"
        return f"from_big_endian_64(xxhash64(to_utf8(concat({tag}, ':', {text}))))"

    def range_rows(self, n: int, alias: str) -> str:
        if self.name == "duckdb":
            return f"range({n}) AS t({alias})"
        return (
            f"UNNEST(sequence(0, {n - 1})) AS t({alias})"
            if n > 0
            else "(SELECT 0 WHERE false) AS t(i)"
        )

    def children(self, count_expr: str) -> str:
        if self.name == "duckdb":
            return f"unnest(range(CAST({count_expr} AS BIGINT)))"
        return f"sequence(0, CAST({count_expr} AS bigint) - 1)"


def _sketch_value(d: _Dialect, sketch: tuple[float, ...], u: str) -> str:
    arr = d.array(sketch)
    x = f"({u} * 100)"
    lo = f"CAST(floor({x}) AS BIGINT)" if d.name == "duckdb" else f"CAST(floor({x}) AS bigint)"
    hi = f"LEAST({lo} + 2, 101)"
    return (
        f"({d.at(arr, f'{lo} + 1')} + ({x} - floor({x})) * "
        f"({d.at(arr, hi)} - {d.at(arr, f'{lo} + 1')}))"
    )


def _pick(choices: tuple[tuple[str | None, float], ...], u: str, otherwise: str) -> str:
    """The value of the share ``u`` falls in, or ``otherwise`` past the last share."""
    if not choices:
        return otherwise
    branches, acc = [], 0.0
    for value, share in choices:
        acc += share
        branches.append(f"WHEN {u} < {acc!r} THEN {_lit(value)}")
    return f"CASE {' '.join(branches)} ELSE {otherwise} END"


def _key_value(d: _Dialect, col: ColumnPlan, index: str) -> str:
    if col.key_shape is not None:
        width = col.key_shape.count("9")
        prefix = col.key_shape.split("9", 1)[0]
        return f"concat({_lit(prefix)}, {d.lpad(index, max(width, 1))})"
    return f"({index} + {col.key_offset})"


def _cast(col: ColumnPlan, expr: str) -> str:
    return f"CAST({expr} AS {col.sql_type})"


def column_expr(d: _Dialect, plan: TablePlan, col: ColumnPlan, key: str, index: str) -> str:
    """The value of ``col`` in the row whose draws are keyed by ``key`` and numbered ``index``."""

    def u(salt: str, k: str = key) -> str:
        return d.uniform(plan.seed, plan.name, col.name, salt, k)

    if col.key:
        value = _cast(col, _key_value(d, col, index))
        return f'{value} AS "{col.name}"'
    if col.marker:
        value = "1"
        if col.null_share > 0:
            value = f"CASE WHEN {u('null')} < {col.null_share!r} THEN NULL ELSE 1 END"
        return f'{value} AS "{col.name}"'
    if col.foreign_key is not None and not col.driving:
        fk = col.foreign_key
        parent_index = f"CAST(floor({u('parent')} * {fk.parent_rows}) AS BIGINT)"
        value = _cast(col, _key_value(d, fk.parent_key, parent_index))
    elif col.foreign_key is not None:
        value = _cast(col, _key_value(d, col.foreign_key.parent_key, "p"))
    else:
        draw_key = key
        if col.pool_shares:
            # A fixed, skewed vocabulary of generated values: the pool index by its share.
            branches, acc = [], 0.0
            for slot, share in enumerate(col.pool_shares[:-1]):
                acc += share
                branches.append(f"WHEN {u('pool')} < {acc!r} THEN {slot}")
            last = len(col.pool_shares) - 1
            draw_key = f"(CASE {' '.join(branches)} ELSE {last} END)" if branches else str(last)
        elif col.pool is not None:
            # A fixed vocabulary: the value is a function of a pool index, not of the row.
            draw_key = f"CAST(floor({u('pool')} * {col.pool}) AS BIGINT)"
        if col.frequencies:
            value = _cast(col, _pick(col.frequencies, u("value"), "NULL"))
        else:
            if col.sketch is not None and col.family in ("numeric", "temporal"):
                raw = _sketch_value(d, col.sketch, u("value", draw_key))
                if col.integer_only:
                    raw = f"round({raw})"
                rest = (
                    d.from_epoch(raw, col.sql_type) if col.family == "temporal" else _cast(col, raw)
                )
            elif col.shapes:
                fills = [
                    (
                        shape,
                        share,
                        d.fill_shape(shape, draw_key, _lit(f"{plan.seed}:{plan.name}:{col.name}")),
                    )
                    for shape, share in col.shapes
                ]
                total = sum(share for _, share, _ in fills)
                branches, acc = [], 0.0
                for _, share, fill in fills[:-1]:
                    acc += share / total
                    branches.append(f"WHEN {u('shape', draw_key)} < {acc!r} THEN {fill}")
                last = fills[-1][2]
                rest = _cast(
                    col, f"CASE {' '.join(branches)} ELSE {last} END" if branches else last
                )
            else:
                rest = "NULL"
            value = rest
    if col.null_share > 0:
        value = f"CASE WHEN {u('null')} < {col.null_share!r} THEN NULL ELSE {value} END"
    return f'{value} AS "{col.name}"'


_PARENT = "__par__"


def _condition_sql(d: _Dialect, condition: str) -> str:
    """A condition over the parent row, in ``d``'s dialect, reading the parent's columns as the
    parent source names them (:func:`_parent_source`)."""
    import sqlglot
    from sqlglot import exp

    tree = sqlglot.parse_one(condition, read="postgres")
    for c in list(tree.find_all(exp.Column)):
        c.replace(exp.column(_PARENT + c.name, quoted=True))
    return tree.sql(dialect=d.name)


def _condition_columns(plan: TablePlan) -> list[str]:
    from provisa.fakes.sql_subset import read

    return sorted({c for k in plan.conditions for c in read(k.condition, group=False).columns})


def _parent_source(d: _Dialect, plan: TablePlan) -> str:
    """The parents the table's rows are generated from, numbered ``p``; where conditions decide
    child counts, each beside its generated row's columns the conditions read."""
    assert plan.fanout is not None
    parents = plan.fanout[0]
    if not plan.conditions:
        return d.range_rows(parents, "p")
    assert plan.parent is not None and plan.parent_key is not None
    key = next(c for c in plan.parent.columns if c.name == plan.parent_key)
    cols = ", ".join(
        f"par.{_quoted(c)} AS {_quoted(_PARENT + c)}" for c in _condition_columns(plan)
    )
    return (
        f"(SELECT t.p AS p, {cols} FROM {d.range_rows(parents, 'p')} "
        f"JOIN ({generation_sql(plan.parent, d.name)}) AS par "
        f"ON par.{_quoted(key.name)} = {_cast(key, _key_value(d, key, 't.p'))}) AS pr"
    )


def _children(d: _Dialect, plan: TablePlan) -> str:
    """Children of parent ``p``: the count of the first condition it meets, else a hot parent's
    own count, else a draw from the fan-out sketch."""
    assert plan.fanout is not None
    _parents, sketch, hot = plan.fanout
    drawn = f"round({_sketch_value(d, sketch, d.uniform(plan.seed, plan.name, '', 'fanout', 'p'))})"
    count = drawn
    if hot:
        branches = " ".join(f"WHEN {i} THEN {n}" for i, n in enumerate(hot))
        count = f"(CASE p {branches} ELSE {drawn} END)"
    if plan.conditions:
        whens = []
        for i, k in enumerate(plan.conditions):
            u = d.uniform(plan.seed, plan.name, "", f"condition{i}", "p")
            if k.fixed is not None:
                n = str(k.fixed)
            elif k.low is not None and k.high is not None:
                n = f"({k.low} + CAST(floor({u} * {k.high - k.low + 1}) AS BIGINT))"
            else:
                assert k.sketch is not None  # a condition's count is fixed, a range or measured
                n = f"round({_sketch_value(d, k.sketch, u)})"
            whens.append(f"WHEN {_condition_sql(d, k.condition)} THEN {n}")
        count = f"(CASE {' '.join(whens)} ELSE {count} END)"
    return count if plan.cap is None else f"LEAST({count}, {plan.cap})"


def children_count_sql(plan: TablePlan, dialect: str) -> str:
    """How many rows the generation statement of a table generated by a relationship yields,
    computed without generating them."""
    d = _Dialect(dialect)
    assert plan.fanout is not None
    # COALESCE: the children of no parents number zero, not NULL.
    return f"SELECT COALESCE(SUM({_children(d, plan)}), 0) AS n FROM {_parent_source(d, plan)}"


def condition_counts_sql(plan: TablePlan, dialect: str) -> str:
    """For the report: each condition's parents -- those whose first met condition it is -- and
    the children they are generated with, one row per condition in order (REQ-1939)."""
    d = _Dialect(dialect)
    count = _children(d, plan)
    parts = []
    for i, k in enumerate(plan.conditions):
        earlier = [f"NOT ({_condition_sql(d, e.condition)})" for e in plan.conditions[:i]]
        met = " AND ".join([f"({_condition_sql(d, k.condition)})", *earlier])
        parts.append(
            f"SELECT {i} AS k, COUNT(*) AS parents, COALESCE(SUM({count}), 0) AS children "
            f"FROM {_parent_source(d, plan)} WHERE {met}"
        )
    return " UNION ALL ".join(parts)


def _quoted(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def _reads_value(c: ColumnPlan) -> bool:
    from provisa.fakes.kinds import Bucket, Hash, Prefix, Truncate

    return isinstance(c.fake.kind, (Bucket, Truncate, Prefix, Hash))


def _with_digests(d: _Dialect, plan: TablePlan, exprs: list[str], key: str) -> list[str]:
    """The digest of each faked column that does not compute from its own value: a draw from
    the row (the others' are of their value, :func:`_faked`)."""
    return exprs + [
        f'{d.digest(plan.seed, plan.name, c.name, key)} AS "{DIGEST}{c.name}"'
        for c in plan.columns
        if c.fake is not None and not _reads_value(c)
    ]


def _after_rules(fakes: dict[str, Any], rules: set[str]) -> set[str]:
    """The faked columns that read a rule's column, directly or through another such fake: they
    are computed after the rules (REQ-1939, GENERATION IN PASSES)."""
    after: set[str] = set()
    grew = True
    while grew:
        grew = False
        for name, col in fakes.items():
            if name not in after and references(col) & (rules | after):
                after.add(name)
                grew = True
    return after


def _faked(
    plan: TablePlan, dialect: str, base: str, child_tables: dict[str, str] | None = None
) -> str:
    """``base`` -- the generated rows, each faked column's digest beside them -- with every fake
    computed over it as a faked read computes it (provisa.fakes.projection.layered), then the
    row-spanning rules this pass computes (provisa.synthetic.group), then the fakes that read
    them, in ``dialect``. ``child_tables`` -- each generated child table's engine address, by its
    dataset name -- is given in the second pass, when the rules reading children are computed;
    before it, a rule reading children keeps its column's drawn value."""
    fakes = {c.name: c.fake for c in plan.columns if c.fake is not None}
    rules = [g for g in plan.group if child_tables is not None or not reads_children(g)]
    if not fakes and not rules:
        return base
    from provisa.fakes.checks import family
    from provisa.transpiler.transpile import transpile, transpile_to_trino

    d = _Dialect(dialect)
    by_value = [
        f'{d.value_digest(plan.seed, plan.name, c.name, _quoted(c.name))} AS "{DIGEST}{c.name}"'
        for c in plan.columns
        if c.fake is not None and _reads_value(c)
    ]
    if by_value:
        base = f"SELECT *, {', '.join(by_value)} FROM ({base}) AS b"
    placeholder = '"__provisa_generated__"'
    columns = [(c.name, c.sql_type, family(c.sql_type)) for c in plan.columns]
    after = _after_rules(fakes, {g.name for g in rules})
    later = tuple(DIGEST + n for n in sorted(after))
    governed = layered(
        f"SELECT * FROM {placeholder}",
        "g",
        columns,
        {n: c for n, c in fakes.items() if n not in after},
        keep=later,
    )
    if rules:
        governed = group_levels(governed, "g", [c.name for c in plan.columns], rules, later)
    if after:
        governed = layered(governed, "g", columns, {n: fakes[n] for n in sorted(after)})
    physical = transpile_to_trino(governed) if dialect == "trino" else transpile(governed, dialect)
    assert physical.count(placeholder) == 1, "the generated rows are read once"
    physical = physical.replace(placeholder, f"({base})")
    for g in rules:
        for link in g.children:
            assert child_tables is not None  # a rule reading children runs in the second pass
            physical = physical.replace(
                child_placeholder(link.child_table), child_tables[link.child_table]
            )
    return physical


def generation_sql(
    plan: TablePlan, dialect: str, child_tables: dict[str, str] | None = None
) -> str:
    """The one statement that generates ``plan``'s rows in ``dialect``; in the second pass,
    ``child_tables`` gives the generated child tables its rules read (:func:`_faked`)."""
    d = _Dialect(dialect)
    if plan.fanout is None:
        exprs = [column_expr(d, plan, c, "i", "i") for c in plan.columns]
        exprs = _with_digests(d, plan, exprs, "i")
        return _faked(
            plan,
            dialect,
            f"SELECT {', '.join(exprs)} FROM {d.range_rows(plan.rows, 'i')}",
            child_tables,
        )
    parents, _sketch, _hot = plan.fanout
    count = _children(d, plan)
    key = "p, j" if d.name == "duckdb" else "concat(CAST(p AS varchar), ':', CAST(j AS varchar))"
    index = "(row_number() OVER (ORDER BY p, j) - 1)"
    exprs = [column_expr(d, plan, c, key, index) for c in plan.columns]
    exprs = _with_digests(d, plan, exprs, key)
    source = _parent_source(d, plan)
    if d.name == "duckdb":
        rows = f"(SELECT p, {d.children(count)} AS j FROM {source}) AS c"
    else:
        rows = f"(SELECT p, j FROM {source} CROSS JOIN UNNEST({d.children(count)}) AS u(j)) AS c"
    return _faked(plan, dialect, f"SELECT {', '.join(exprs)} FROM {rows}", child_tables)
