# Copyright (c) 2026 Kenneth Stott
# Canary: 3d8f1a27-6c94-4e0b-b2d5-a7e1c9f04b38
#
# This source code is licensed under the Business Source License 1.1
# found in the LICENSE file in the root directory of this source tree.
#
# NOTICE: Use of this software for training artificial intelligence or
# machine learning models is strictly prohibited without explicit written
# permission from the copyright holder.

"""The generation statement of one synthetic table (REQ-1939).

A synthetic table is generated by ONE SELECT the engine runs: nothing is read, every value is a
pure function of the dataset's seed, the table, the column and the row, so the same seed and scale
give the same rows on every run. Uniform draws are hashes of those inputs; each column maps its
uniforms through what its profile recorded:

* a key column takes the row number (offset into its profiled range), so it is unique;
* a foreign key of the table's driving relationship is its parent's key, the table's rows being
  generated parent by parent with a child count drawn from the relationship's profiled fan-out
  sketch, and the hot parents -- the most frequent keys of the child's column, beyond what the
  sketch resolves -- given their own scaled child counts, so join fan-out and its skew survive; another foreign key draws its parent
  uniformly over the parent's generated keys;
* a column declaring the categories fake draws the operator's listed values (REQ-1494), and a
  boolean its two values, by their frequencies;
* a column with a full value-frequency table and no fake keeps its number of distinct values and
  their shares on generated values;
* any other column draws through its 101-point quantile sketch (numeric, temporal) or its value
  shapes (text), never from its recorded most frequent values;
* a column whose distinct count does not grow with its rows draws from a fixed pool of that many
  values, so its vocabulary size is kept at any scale;
* null shares are kept, and an integer-only column stays integral.

The statement is written in the engine's dialect: DuckDB (the test stack's engine) and Trino.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from provisa.fakes.projection import DIGEST, layered, references
from provisa.synthetic.group import (
    GroupColumn,
    child_placeholder,
    group_levels,
    reads_children,
)

DIALECTS = ("duckdb", "trino")

_TWO_64 = "18446744073709551616.0"


@dataclass(frozen=True)
class ForeignKey:
    """A column drawing its value from a parent's generated keys."""

    parent_table: str
    parent_rows: int
    parent_key: "ColumnPlan"


@dataclass(frozen=True)
class ColumnPlan:
    name: str
    sql_type: str  # the engine type the value is cast to
    family: str  # numeric | temporal | text | boolean | other
    null_share: float = 0.0
    key: bool = False
    key_offset: int = 0  # an integer key starts here (its profiled minimum)
    key_shape: str | None = None  # a text key fills this shape with the row number
    foreign_key: ForeignKey | None = None
    driving: bool = False  # the foreign key of the relationship the rows are generated by
    frequencies: tuple[tuple[str | None, float], ...] = ()  # the whole vocabulary, by share
    sketch: tuple[float, ...] | None = None  # 101 points
    shapes: tuple[tuple[str, float], ...] = ()  # by share
    integer_only: bool = False
    pool: int | None = None  # a fixed vocabulary of this many values; None grows with rows
    # The shares of the pool's values, most frequent first: a skewed vocabulary keeps its skew on
    # generated values (empty: the pool's values are equally likely).
    pool_shares: tuple[float, ...] = ()
    # REQ-1494, REQ-1939: the column's synthetic rule, else its fake, computed over the generated
    # row as a faked read computes it (provisa.fakes.read_sql.Column); None for none.
    fake: Any = None
    # The row's value is only whether it is NULL (1, or NULL at the null share): the fake decides
    # every value and reads no generated value of its own column.
    marker: bool = False
    # REQ-1939, DEPENDENCE KEPT: the real values a pool's slots stand for (never generated), and
    # the column holding the uniform point its value is drawn at when dependence decides it.
    pool_values: tuple[str, ...] = ()
    dep_u: str | None = None


@dataclass(frozen=True)
class PlannedCondition:
    """A conditional child count (REQ-1939, CONDITIONAL FAN-OUT): ``condition`` over the parent
    row, in the governed dialect, and the count a parent meeting it takes -- ``fixed``, a ``low``
    to ``high`` range drawn evenly, or a draw from ``sketch``, the fan-out measured for the real
    parents meeting it."""

    condition: str
    fixed: int | None = None
    low: int | None = None
    high: int | None = None
    sketch: tuple[float, ...] | None = None


@dataclass(frozen=True)
class TablePlan:
    name: str  # the table as the dataset names it (salts every draw)
    rows: int  # for a table generated row by row
    columns: tuple[ColumnPlan, ...]
    # The relationship the rows are generated by: (parent rows, the fan-out sketch, and the child
    # counts of its hot parents -- the first parents generated, one each -- beyond the sketch).
    fanout: tuple[int, tuple[float, ...], tuple[int, ...]] | None = None
    seed: int = 0
    notes: tuple[str, ...] = field(default=())
    # REQ-1494, REQ-1939: the row-spanning rules (provisa.synthetic.group), computed over the
    # generated rows; and the most children a parent has, where a sequence's entity is the
    # relationship the rows are generated by (no entity holds more rows than states).
    group: tuple[GroupColumn, ...] = ()
    cap: int | None = None
    # The relationship's conditional child counts, the parent's plan (whose rows the conditions
    # read, generated again inside this statement: the same rows, by the same seed) and the
    # parent's key column.
    conditions: tuple[PlannedCondition, ...] = ()
    parent: "TablePlan | None" = None
    parent_key: str | None = None
    # REQ-1939, DEPENDENCE KEPT: the copula and network the columns are drawn by
    # (provisa.synthetic.dependence.DependencePlan); None where the run measured none.
    dependence: Any = None
    # REQ-1939, NOT TOO CLOSE TO A REAL ROW: the draw the rows' values are drawn by (0: the
    # first), and the columns every draw gives one value -- those a child's conditions or
    # dependence read, which decide its rows, and what they are computed from.
    draw: int = 0
    fixed: frozenset[str] = frozenset()


def _redraw(plan: TablePlan, column: str, salt: str) -> str:
    """``salt`` for ``column``'s value draw in the plan's draw: the first draw's salt as it is,
    a later draw's its own -- a column every draw fixes excepted."""
    if plan.draw == 0 or column in plan.fixed:
        return salt
    return f"{salt}#r{plan.draw}"


def _lit(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


class _Dialect:
    def __init__(self, name: str) -> None:
        if name not in DIALECTS:
            raise ValueError(
                f"no synthetic generation for engine dialect {name!r}; one of {DIALECTS}"
            )
        self.name = name

    def uniform(self, seed: int, table: str, column: str, salt: str, key: str) -> str:
        """A uniform draw in [0, 1) from the seed, table, column, a salt and the row key."""
        tag = _lit(f"{seed}:{table}:{column}:{salt}")
        if self.name == "duckdb":
            # One string hashed: DuckDB's hash of several arguments combines their hashes, so two
            # columns' draws for one row would be related.
            return f"(hash(concat_ws(':', {tag}, {key})) / {_TWO_64})"
        return (
            f"(CAST(from_big_endian_64(xxhash64(to_utf8(concat({tag}, ':', CAST({key} AS varchar)))))"
            f" AS double) / {_TWO_64} + 0.5)"
        )

    def array(self, values: tuple[float, ...]) -> str:
        body = ", ".join(repr(float(v)) for v in values)
        return f"[{body}]" if self.name == "duckdb" else f"ARRAY[{body}]"

    def at(self, arr: str, index: str) -> str:
        """1-based element ``index`` of ``arr``."""
        return (
            f"list_extract({arr}, {index})"
            if self.name == "duckdb"
            else f"element_at({arr}, {index})"
        )

    def from_epoch(self, expr: str, sql_type: str) -> str:
        ts = f"to_timestamp({expr})" if self.name == "duckdb" else f"from_unixtime({expr})"
        return f"CAST({ts} AS {sql_type})"

    def fill_shape(self, shape: str, key: str, salt_seed: str) -> str:
        """``shape`` with each ``A``/``a``/``9`` replaced by a letter or digit drawn from ``key``."""
        pos = "_pos"
        if self.name == "duckdb":
            draw = f"hash(concat_ws(':', {salt_seed}, {key}, {pos}))"
            return (
                f"array_to_string(list_transform(range(length({_lit(shape)})), {pos} -> "
                f"CASE substr({_lit(shape)}, {pos} + 1, 1) "
                f"WHEN 'A' THEN chr(65 + CAST({draw} % 26 AS INTEGER)) "
                f"WHEN 'a' THEN chr(97 + CAST({draw} % 26 AS INTEGER)) "
                f"WHEN '9' THEN chr(48 + CAST({draw} % 10 AS INTEGER)) "
                f"ELSE substr({_lit(shape)}, {pos} + 1, 1) END), '')"
            )
        draw = (
            f"abs(from_big_endian_64(xxhash64(to_utf8(concat({salt_seed}, ':', "
            f"CAST({key} AS varchar), ':', CAST({pos} AS varchar))))))"
        )
        return (
            f"array_join(transform(sequence(1, length({_lit(shape)})), {pos} -> "
            f"CASE substr({_lit(shape)}, {pos}, 1) "
            f"WHEN 'A' THEN chr(65 + CAST({draw} % 26 AS integer)) "
            f"WHEN 'a' THEN chr(97 + CAST({draw} % 26 AS integer)) "
            f"WHEN '9' THEN chr(48 + CAST({draw} % 10 AS integer)) "
            f"ELSE substr({_lit(shape)}, {pos}, 1) END), '')"
        )

    def digest(self, seed: int, table: str, column: str, key: str) -> str:
        """A signed 64-bit draw from the seed, table, column and row key: the digest a fake
        computed in generation is seeded by, as a faked read's is by the real value (REQ-1939)."""
        tag = _lit(f"{seed}:{table}:{column}:fake")
        if self.name == "duckdb":
            return f"CAST(hash(concat_ws(':', {tag}, {key})) >> 1 AS BIGINT)"
        return f"from_big_endian_64(xxhash64(to_utf8(concat({tag}, ':', CAST({key} AS varchar)))))"

    def lpad(self, expr: str, width: int) -> str:
        # Never truncated: a number longer than the shape's digits keeps every digit, so keys
        # filled into a shape stay unique at any row count.
        text = f"CAST({expr} AS varchar)"
        return (
            f"(CASE WHEN length({text}) >= {width} THEN {text} ELSE lpad({text}, {width}, '0') END)"
        )

    def value_digest(self, seed: int, table: str, column: str, value: str) -> str:
        """A signed 64-bit draw from the seed, table, column and a generated value: the digest
        of a fake that computes from the column's own value (bucket, truncate, prefix, hash), so
        one value gives one fake, as a faked read's digest of the real value does."""
        tag = _lit(f"{seed}:{table}:{column}:value")
        text = f"CAST({value} AS varchar)"
        if self.name == "duckdb":
            return f"CAST(hash(concat_ws(':', {tag}, {text})) >> 1 AS BIGINT)"
        return f"from_big_endian_64(xxhash64(to_utf8(concat({tag}, ':', {text}))))"

    def range_rows(self, n: int, alias: str) -> str:
        if self.name == "duckdb":
            return f"range({n}) AS t({alias})"
        return (
            f"UNNEST(sequence(0, {n - 1})) AS t({alias})"
            if n > 0
            else "(SELECT 0 WHERE false) AS t(i)"
        )

    def children(self, count_expr: str) -> str:
        if self.name == "duckdb":
            return f"unnest(range(CAST({count_expr} AS BIGINT)))"
        return f"sequence(0, CAST({count_expr} AS bigint) - 1)"


def _sketch_value(d: _Dialect, sketch: tuple[float, ...], u: str) -> str:
    arr = d.array(sketch)
    x = f"({u} * 100)"
    lo = f"CAST(floor({x}) AS BIGINT)" if d.name == "duckdb" else f"CAST(floor({x}) AS bigint)"
    hi = f"LEAST({lo} + 2, 101)"
    return (
        f"({d.at(arr, f'{lo} + 1')} + ({x} - floor({x})) * "
        f"({d.at(arr, hi)} - {d.at(arr, f'{lo} + 1')}))"
    )


def _pick(choices: tuple[tuple[str | None, float], ...], u: str, otherwise: str) -> str:
    """The value of the share ``u`` falls in, or ``otherwise`` past the last share."""
    if not choices:
        return otherwise
    branches, acc = [], 0.0
    for value, share in choices:
        acc += share
        branches.append(f"WHEN {u} < {acc!r} THEN {_lit(value)}")
    return f"CASE {' '.join(branches)} ELSE {otherwise} END"


def _key_value(d: _Dialect, col: ColumnPlan, index: str) -> str:
    if col.key_shape is not None:
        width = col.key_shape.count("9")
        prefix = col.key_shape.split("9", 1)[0]
        return f"concat({_lit(prefix)}, {d.lpad(index, max(width, 1))})"
    return f"({index} + {col.key_offset})"


def _cast(col: ColumnPlan, expr: str) -> str:
    return f"CAST({expr} AS {col.sql_type})"


def column_expr(d: _Dialect, plan: TablePlan, col: ColumnPlan, key: str, index: str) -> str:
    """The value of ``col`` in the row whose draws are keyed by ``key`` and numbered ``index``."""

    def u(salt: str, k: str = key) -> str:
        # A non-driving foreign key's parent is structure, drawn once (REQ-1939, NOT TOO CLOSE).
        drawn = salt if salt == "parent" else _redraw(plan, col.name, salt)
        return d.uniform(plan.seed, plan.name, col.name, drawn, k)

    if col.key:
        value = _cast(col, _key_value(d, col, index))
        return f'{value} AS "{col.name}"'
    if col.marker:
        value = "1"
        if col.null_share > 0:
            value = f"CASE WHEN {u('null')} < {col.null_share!r} THEN NULL ELSE 1 END"
        return f'{value} AS "{col.name}"'
    if col.foreign_key is not None and not col.driving:
        fk = col.foreign_key
        parent_index = f"CAST(floor({u('parent')} * {fk.parent_rows}) AS BIGINT)"
        value = _cast(col, _key_value(d, fk.parent_key, parent_index))
    elif col.foreign_key is not None:
        value = _cast(col, _key_value(d, col.foreign_key.parent_key, "p"))
    else:
        draw_key = key
        if col.pool_shares:
            # A fixed, skewed vocabulary of generated values: the pool index by its share.
            branches, acc = [], 0.0
            slot_u = col.dep_u or u("pool")
            for slot, share in enumerate(col.pool_shares[:-1]):
                acc += share
                branches.append(f"WHEN {slot_u} < {acc!r} THEN {slot}")
            last = len(col.pool_shares) - 1
            draw_key = f"(CASE {' '.join(branches)} ELSE {last} END)" if branches else str(last)
        elif col.pool is not None:
            # A fixed vocabulary: the value is a function of a pool index, not of the row.
            draw_key = f"CAST(floor({u('pool')} * {col.pool}) AS BIGINT)"
        if col.frequencies:
            value = _cast(col, _pick(col.frequencies, col.dep_u or u("value"), "NULL"))
        else:
            if col.sketch is not None and col.family in ("numeric", "temporal"):
                raw = _sketch_value(d, col.sketch, col.dep_u or u("value", draw_key))
                if col.integer_only:
                    raw = f"round({raw})"
                rest = (
                    d.from_epoch(raw, col.sql_type) if col.family == "temporal" else _cast(col, raw)
                )
            elif col.shapes:
                fills = [
                    (
                        shape,
                        share,
                        d.fill_shape(
                            shape,
                            draw_key,
                            _lit(_redraw(plan, col.name, f"{plan.seed}:{plan.name}:{col.name}")),
                        ),
                    )
                    for shape, share in col.shapes
                ]
                total = sum(share for _, share, _ in fills)
                branches, acc = [], 0.0
                for _, share, fill in fills[:-1]:
                    acc += share / total
                    branches.append(f"WHEN {u('shape', draw_key)} < {acc!r} THEN {fill}")
                last = fills[-1][2]
                rest = _cast(
                    col, f"CASE {' '.join(branches)} ELSE {last} END" if branches else last
                )
            else:
                rest = "NULL"
            value = rest
    if col.null_share > 0:
        value = f"CASE WHEN {u('null')} < {col.null_share!r} THEN NULL ELSE {value} END"
    return f'{value} AS "{col.name}"'


_PARENT = "__par__"


def _condition_sql(d: _Dialect, condition: str) -> str:
    """A condition over the parent row, in ``d``'s dialect, reading the parent's columns as the
    parent source names them (:func:`_parent_source`)."""
    import sqlglot
    from sqlglot import exp

    tree = sqlglot.parse_one(condition, read="postgres")
    for c in list(tree.find_all(exp.Column)):
        c.replace(exp.column(_PARENT + c.name, quoted=True))
    return tree.sql(dialect=d.name)


def _dependence_parent_columns(plan: TablePlan) -> list[str]:
    dep = plan.dependence
    if dep is None:
        return []
    return [r[1] for x in dep.targets for r in x.parents if not isinstance(r, str)]


def _lit_state(state: Any) -> str:
    return str(int(state)) if isinstance(state, int) else _lit(str(state))


def _state_pick(u: str, shares: list[tuple[Any, float]]) -> str:
    """The state whose cumulative share first exceeds ``u``."""
    if not shares:
        return "NULL"
    whens, acc = [], 0.0
    for s, share in shares[:-1]:
        acc += share
        whens.append(f"WHEN {u} < {acc!r} THEN {_lit_state(s)}")
    last = _lit_state(shares[-1][0])
    return f"(CASE {' '.join(whens)} ELSE {last} END)" if whens else last


def _node_state(node: Any, u: str) -> str:
    if node.kind == "number":
        return f"LEAST(CAST(FLOOR({u} * 10) AS BIGINT), 9)"
    whens = " ".join(
        f"WHEN {u} < {start + width!r} THEN {'NULL' if v is None else _lit(str(v))}"
        for v, start, width in node.slices
    )
    return f"(CASE {whens} ELSE NULL END)"


def _target_u(node: Any, state: str, u2: str) -> str:
    """A uniform point inside the target state's slice: a value of that state, drawn evenly."""
    if node.kind == "number":
        return f"(({state} + {u2}) / 10.0)"
    whens = " ".join(
        f"WHEN {_lit(str(v))} THEN {start!r} + {u2} * {width!r}"
        for v, start, width in node.slices
        if v is not None
    )
    return f"(CASE {state} {whens} ELSE {u2} END)"


def _parent_state(ref: Any) -> str:
    """A parent table's column's state, read off the joined parent row."""
    _tag, column, deciles = ref
    value = _quoted(_PARENT + column)
    if deciles is None:
        return f"CAST({value} AS VARCHAR)"
    whens = " ".join(f"WHEN {value} < {q!r} THEN {i}" for i, q in enumerate(deciles))
    return f"(CASE {whens} ELSE 9 END)"


def _dependence_levels(d: _Dialect, plan: TablePlan, rows: str, alias: str, key: str) -> str:
    """``rows`` -- a table expression of the rows, aliased ``alias`` -- with, for every column
    dependence decides, its uniform point ``__U__<column>`` and its state ``__st__<column>``
    (REQ-1939, DEPENDENCE KEPT): the copula's correlated points, the other nodes' own, then each
    network target's state from the joint counts given its parents' states, and its point in that
    state."""
    from provisa.fakes.read_sql import inverse_normal_sql
    from provisa.synthetic.dependence import normal_cdf_sql

    dep = plan.dependence
    # The copula and network draw together: a later draw redraws them all, unless one of their
    # columns is fixed (REQ-1939, NOT TOO CLOSE TO A REAL ROW).
    held = plan.draw == 0 or bool(set(dep.nodes) & plan.fixed)

    def uni(column: str, salt: str) -> str:
        return d.uniform(
            plan.seed, plan.name, column, salt if held else f"{salt}#r{plan.draw}", key
        )

    levels: list[list[str]] = []
    if dep.copula:
        levels.append(
            [
                f"{inverse_normal_sql(uni(c, 'copula'))} AS {_quoted('__z__' + c)}"
                for c in dep.copula
            ]
        )
        cu = []
        for i, c in enumerate(dep.copula):
            mix = " + ".join(
                f"{w!r} * {_quoted('__z__' + dep.copula[k])}"
                for k, w in enumerate(dep.factor[i])
                if k <= i and w != 0.0
            )
            cu.append(f"{normal_cdf_sql('(' + mix + ')')} AS {_quoted('__U__' + c)}")
        levels.append(cu)
    targets = {x.name for x in dep.targets}
    own = []
    for name, node in sorted(dep.nodes.items()):
        if name in targets:
            continue
        u = _quoted("__U__" + name) if name in dep.copula else uni(name, node.own_salt)
        if name not in dep.copula:
            own.append(f"{u} AS {_quoted('__U__' + name)}")
        own.append(f"{_node_state(node, u)} AS {_quoted('__st__' + name)}")
    if own:
        levels.append(own)
    for x in dep.targets:
        node = dep.nodes[x.name]
        states = [
            _quoted("__st__" + r) if isinstance(r, str) else _parent_state(r) for r in x.parents
        ]
        u_net = uni(x.name, "network")
        whens = []
        for combo, shares in sorted(x.given.items(), key=lambda kv: str(kv[0])):
            if any(s is None for s in combo):
                continue
            cond = " AND ".join(f"{st} = {_lit_state(s)}" for st, s in zip(states, combo))
            whens.append(f"WHEN {cond} THEN {_state_pick(u_net, shares)}")
        state = (
            f"(CASE {' '.join(whens)} ELSE {_state_pick(u_net, x.marginal)} END)"
            if whens
            else _state_pick(u_net, x.marginal)
        )
        levels.append([f"{state} AS {_quoted('__st__' + x.name)}"])
        levels.append(
            [
                f"{_target_u(node, _quoted('__st__' + x.name), uni(x.name, 'network2'))} "
                f"AS {_quoted('__U__' + x.name)}"
            ]
        )
    out = f"(SELECT * FROM {rows})"
    for n, exprs in enumerate(levels):
        out = f"(SELECT *, {', '.join(exprs)} FROM {out} AS dl{n})"
    return f"{out} AS {alias}"


def _condition_columns(plan: TablePlan) -> list[str]:
    from provisa.fakes.sql_subset import read

    return sorted({c for k in plan.conditions for c in read(k.condition, group=False).columns})


def _parent_source(d: _Dialect, plan: TablePlan) -> str:
    """The parents the table's rows are generated from, numbered ``p``; where conditions decide
    child counts, each beside its generated row's columns the conditions read."""
    assert plan.fanout is not None
    parents = plan.fanout[0]
    if plan.parent is None:
        return d.range_rows(parents, "p")
    assert plan.parent_key is not None
    key = next(c for c in plan.parent.columns if c.name == plan.parent_key)
    read = sorted(set(_condition_columns(plan)) | set(_dependence_parent_columns(plan)))
    cols = ", ".join(f"par.{_quoted(c)} AS {_quoted(_PARENT + c)}" for c in read)
    return (
        f"(SELECT t.p AS p, {cols} FROM {d.range_rows(parents, 'p')} "
        f"JOIN ({generation_sql(plan.parent, d.name)}) AS par "
        f"ON par.{_quoted(key.name)} = {_cast(key, _key_value(d, key, 't.p'))}) AS pr"
    )


def _children(d: _Dialect, plan: TablePlan) -> str:
    """Children of parent ``p``: the count of the first condition it meets, else a hot parent's
    own count, else a draw from the fan-out sketch."""
    assert plan.fanout is not None
    _parents, sketch, hot = plan.fanout
    drawn = f"round({_sketch_value(d, sketch, d.uniform(plan.seed, plan.name, '', 'fanout', 'p'))})"
    count = drawn
    if hot:
        branches = " ".join(f"WHEN {i} THEN {n}" for i, n in enumerate(hot))
        count = f"(CASE p {branches} ELSE {drawn} END)"
    if plan.conditions:
        whens = []
        for i, k in enumerate(plan.conditions):
            u = d.uniform(plan.seed, plan.name, "", f"condition{i}", "p")
            if k.fixed is not None:
                n = str(k.fixed)
            elif k.low is not None and k.high is not None:
                n = f"({k.low} + CAST(floor({u} * {k.high - k.low + 1}) AS BIGINT))"
            else:
                assert k.sketch is not None  # a condition's count is fixed, a range or measured
                n = f"round({_sketch_value(d, k.sketch, u)})"
            whens.append(f"WHEN {_condition_sql(d, k.condition)} THEN {n}")
        count = f"(CASE {' '.join(whens)} ELSE {count} END)"
    return count if plan.cap is None else f"LEAST({count}, {plan.cap})"


def children_count_sql(plan: TablePlan, dialect: str) -> str:
    """How many rows the generation statement of a table generated by a relationship yields,
    computed without generating them."""
    d = _Dialect(dialect)
    assert plan.fanout is not None
    # COALESCE: the children of no parents number zero, not NULL.
    return f"SELECT COALESCE(SUM({_children(d, plan)}), 0) AS n FROM {_parent_source(d, plan)}"


def condition_counts_sql(plan: TablePlan, dialect: str) -> str:
    """For the report: each condition's parents -- those whose first met condition it is -- and
    the children they are generated with, one row per condition in order (REQ-1939)."""
    d = _Dialect(dialect)
    count = _children(d, plan)
    parts = []
    for i, k in enumerate(plan.conditions):
        earlier = [f"NOT ({_condition_sql(d, e.condition)})" for e in plan.conditions[:i]]
        met = " AND ".join([f"({_condition_sql(d, k.condition)})", *earlier])
        parts.append(
            f"SELECT {i} AS k, COUNT(*) AS parents, COALESCE(SUM({count}), 0) AS children "
            f"FROM {_parent_source(d, plan)} WHERE {met}"
        )
    return " UNION ALL ".join(parts)


def _quoted(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def _reads_value(c: ColumnPlan) -> bool:
    from provisa.fakes.kinds import Bucket, Hash, Prefix, Truncate

    return isinstance(c.fake.kind, (Bucket, Truncate, Prefix, Hash))


def _with_digests(d: _Dialect, plan: TablePlan, exprs: list[str], key: str) -> list[str]:
    """The digest of each faked column that does not compute from its own value: a draw from
    the row (the others' are of their value, :func:`_faked`)."""
    return exprs + [
        f'{d.digest(plan.seed, plan.name, c.name, key)} AS "{DIGEST}{c.name}"'
        for c in plan.columns
        if c.fake is not None and not _reads_value(c)
    ]


def _after_rules(fakes: dict[str, Any], rules: set[str]) -> set[str]:
    """The faked columns that read a rule's column, directly or through another such fake: they
    are computed after the rules (REQ-1939, GENERATION IN PASSES)."""
    after: set[str] = set()
    grew = True
    while grew:
        grew = False
        for name, col in fakes.items():
            if name not in after and references(col) & (rules | after):
                after.add(name)
                grew = True
    return after


def _decided_points(plan: TablePlan) -> list[str]:
    """The uniform points dependence decides for faked columns, carried to the fakes' layers."""
    return [
        f"{c.dep_u} AS {c.dep_u}"
        for c in plan.columns
        if c.fake is not None and c.dep_u is not None
    ]


def _faked(
    plan: TablePlan,
    dialect: str,
    base: str,
    child_tables: dict[str, str] | None = None,
    carry: tuple[str, ...] = (),
) -> str:
    """``base`` -- the generated rows, each faked column's digest beside them -- with every fake
    computed over it as a faked read computes it (provisa.fakes.projection.layered), then the
    row-spanning rules this pass computes (provisa.synthetic.group), then the fakes that read
    them, in ``dialect``. ``child_tables`` -- each generated child table's engine address, by its
    dataset name -- is given in the second pass, when the rules reading children are computed;
    before it, a rule reading children keeps its column's drawn value. ``carry`` names further
    columns of ``base`` carried through."""
    fakes = {c.name: c.fake for c in plan.columns if c.fake is not None}
    rules = [g for g in plan.group if child_tables is not None or not reads_children(g)]
    if not fakes and not rules:
        return base
    from provisa.fakes.checks import family
    from provisa.transpiler.transpile import transpile, transpile_to_trino

    d = _Dialect(dialect)
    by_value = [
        f'{d.value_digest(plan.seed, plan.name, c.name, _quoted(c.name))} AS "{DIGEST}{c.name}"'
        for c in plan.columns
        if c.fake is not None and _reads_value(c)
    ]
    if by_value:
        base = f"SELECT *, {', '.join(by_value)} FROM ({base}) AS b"
    placeholder = '"__provisa_generated__"'
    columns = [(c.name, c.sql_type, family(c.sql_type)) for c in plan.columns]
    after = _after_rules(fakes, {g.name for g in rules})
    later = tuple(DIGEST + n for n in sorted(after))
    # REQ-1939, DEPENDENCE KEPT: a faked column the copula or network draws takes that point.
    points = {c.name: c.dep_u for c in plan.columns if c.fake is not None and c.dep_u is not None}
    governed = layered(
        f"SELECT * FROM {placeholder}",
        "g",
        columns,
        {n: c for n, c in fakes.items() if n not in after},
        keep=later + tuple(p.strip('"') for n, p in points.items() if n in after) + carry,
        uniforms={n: p for n, p in points.items() if n not in after},
    )
    if rules:
        governed = group_levels(governed, "g", [c.name for c in plan.columns], rules, later + carry)
    if after:
        governed = layered(
            governed,
            "g",
            columns,
            {n: fakes[n] for n in sorted(after)},
            keep=carry,
            uniforms={n: p for n, p in points.items() if n in after},
        )
    physical = transpile_to_trino(governed) if dialect == "trino" else transpile(governed, dialect)
    assert physical.count(placeholder) == 1, "the generated rows are read once"
    physical = physical.replace(placeholder, f"({base})")
    for g in rules:
        for link in g.children:
            assert child_tables is not None  # a rule reading children runs in the second pass
            physical = physical.replace(
                child_placeholder(link.child_table), child_tables[link.child_table]
            )
    return physical


RID = "__rid"


def generation_sql(
    plan: TablePlan, dialect: str, child_tables: dict[str, str] | None = None, rid: bool = False
) -> str:
    """The one statement that generates ``plan``'s rows in ``dialect``; in the second pass,
    ``child_tables`` gives the generated child tables its rules read (:func:`_faked`). ``rid``:
    each row also carries its number as ``__rid``, the same in every draw."""
    d = _Dialect(dialect)
    carry = (RID,) if rid else ()
    if plan.fanout is None:
        exprs = [column_expr(d, plan, c, "i", "i") for c in plan.columns]
        exprs = _with_digests(d, plan, exprs, "i") + _decided_points(plan)
        if rid:
            exprs.append(f"i AS {_quoted(RID)}")
        rows = d.range_rows(plan.rows, "i")
        if plan.dependence is not None:
            rows = _dependence_levels(d, plan, rows, "t", "i")
        return _faked(plan, dialect, f"SELECT {', '.join(exprs)} FROM {rows}", child_tables, carry)
    parents, _sketch, _hot = plan.fanout
    count = _children(d, plan)
    key = "p, j" if d.name == "duckdb" else "concat(CAST(p AS varchar), ':', CAST(j AS varchar))"
    index = "(row_number() OVER (ORDER BY p, j) - 1)"
    exprs = [column_expr(d, plan, c, key, index) for c in plan.columns]
    exprs = _with_digests(d, plan, exprs, key) + _decided_points(plan)
    if rid:
        exprs.append(f"{index} AS {_quoted(RID)}")
    source = _parent_source(d, plan)
    # Every column of the parent rows is carried: the conditions and the dependence read them.
    if d.name == "duckdb":
        rows = f"(SELECT *, {d.children(count)} AS j FROM {source}) AS c"
    else:
        rows = f"(SELECT * FROM {source} CROSS JOIN UNNEST({d.children(count)}) AS u(j)) AS c"
    if plan.dependence is not None:
        rows = _dependence_levels(d, plan, rows, "c", key)
    return _faked(plan, dialect, f"SELECT {', '.join(exprs)} FROM {rows}", child_tables, carry)


# -- not too close to a real row (REQ-1939; maintainer rulings W1, Z2, C1) -----------------------

SAMPLE_ID = "__sid"


@dataclass(frozen=True)
class DistanceColumn:
    """A column the distance between a generated and a real row reads: a number (temporal as
    seconds since the epoch) apart by its difference over ``scale``, the real sample's
    interquartile range; a category, or a number whose sample has none, apart by 1 unless equal.
    The sample holds it as ``__d<position>``, a double or text."""

    name: str
    family: str  # numeric | temporal | text | boolean | other
    scale: float | None  # None: equal or not
    sql_type: str = ""


@dataclass(frozen=True)
class Closeness:
    """How a table's rows are kept from its real rows: ``draws`` draws of each row's values, the
    first whose nearest real row in ``sample`` (the real sample's engine address) is at least
    ``threshold`` away kept, a row with none dropped; and the parents -- (foreign key column,
    the parent's generated table's address, its key column) -- a row is dropped without, a
    dropped row's children dropping with it (C1)."""

    sample: str
    threshold: float
    draws: int
    columns: tuple[DistanceColumn, ...]
    parents: tuple[tuple[str, str, str], ...] = ()


def distance_columns(plan: TablePlan) -> list[ColumnPlan]:
    """The columns drawn from the real values: no key, foreign key, fake or rule decides them --
    a rule spanning rows among them, computed in the plan's group, not as its column's fake."""
    rules = {g.name for g in plan.group}
    return [
        c
        for c in plan.columns
        if not c.key
        and c.foreign_key is None
        and c.fake is None
        and not c.marker
        and c.name not in rules
    ]


def comparable(d: _Dialect, col: DistanceColumn, expr: str) -> str:
    """``expr`` as the sample holds the column: a double, or text."""
    if col.family == "numeric":
        return f"CAST({expr} AS DOUBLE)"
    if col.family == "temporal":
        if d.name == "duckdb":
            return f"CAST(epoch({expr}) AS DOUBLE)"
        if "zone" in col.sql_type.lower():
            return f"CAST(to_unixtime({expr}) AS DOUBLE)"
        return f"CAST(to_unixtime(with_timezone(CAST({expr} AS timestamp(6)), 'UTC')) AS DOUBLE)"
    return f"CAST({expr} AS VARCHAR)"


def _distance(cols: tuple[DistanceColumn, ...], a: str, b: str) -> str:
    """The mean of the columns' distances between rows ``a`` and ``b`` (both NULL: 0; one: 1)."""
    parts = []
    for i, c in enumerate(cols):
        x, y = f"{a}.{_quoted(f'__d{i}')}", f"{b}.{_quoted(f'__d{i}')}"
        if c.scale is not None:
            parts.append(
                f"COALESCE(ABS({x} - {y}) / {c.scale!r}, "
                f"CASE WHEN {x} IS NULL AND {y} IS NULL THEN 0.0 ELSE 1.0 END)"
            )
        else:
            parts.append(f"(CASE WHEN {x} IS NOT DISTINCT FROM {y} THEN 0.0 ELSE 1.0 END)")
    return f"(({' + '.join(parts)}) / {len(parts)}.0)"


def _kept_by_parents(close: Closeness, alias: str) -> str:
    """Every foreign key's parent kept (or none referred to)."""
    terms = [
        f"({alias}.{_quoted(fk)} IS NULL OR {alias}.{_quoted(fk)} IN "
        f"(SELECT pk.{_quoted(key)} FROM {address} AS pk))"
        for fk, address, key in close.parents
    ]
    return " AND ".join(terms) if terms else "TRUE"


def _candidates(
    plan: TablePlan, dialect: str, close: Closeness, child_tables: dict[str, str] | None
) -> str:
    """The WITH clause: every draw of every row (``cand``), each draw's distance to its nearest
    real row (``nn``) and the draw each row keeps (``pick``): its first far enough."""
    from dataclasses import replace

    d = _Dialect(dialect)
    draws = " UNION ALL ".join(
        f"SELECT {r} AS {_quoted('__draw')}, g.* FROM "
        f"({generation_sql(replace(plan, draw=r), dialect, child_tables, rid=True)}) AS g"
        for r in range(close.draws)
    )
    values = ", ".join(
        f"{comparable(d, c, _quoted(c.name))} AS {_quoted(f'__d{i}')}"
        for i, c in enumerate(close.columns)
    )
    rid, draw = _quoted(RID), _quoted("__draw")
    return (
        f"WITH cand AS ({draws}), "
        f"ct AS (SELECT {rid}, {draw}, {values} FROM cand), "
        f"nn AS (SELECT ct.{rid}, ct.{draw}, MIN({_distance(close.columns, 'ct', 's')}) AS nn "
        f"FROM ct CROSS JOIN {close.sample} AS s GROUP BY ct.{rid}, ct.{draw}), "
        f"pick AS (SELECT {rid}, MIN({draw}) AS {draw} FROM nn WHERE nn >= {close.threshold!r} "
        f"GROUP BY {rid})"
    )


def closeness_sql(
    plan: TablePlan, dialect: str, close: Closeness, child_tables: dict[str, str] | None = None
) -> str:
    """The table's rows, each its first draw far enough from every real row, those with none
    and those whose parent was dropped left out (REQ-1939, NOT TOO CLOSE TO A REAL ROW). A table
    with no column drawn from real values keeps its rows, its parents' drops excepted."""
    cols = ", ".join(f"c.{_quoted(c.name)}" for c in plan.columns)
    if not close.columns:
        return (
            f"SELECT {cols} FROM ({generation_sql(plan, dialect, child_tables)}) AS c "
            f"WHERE {_kept_by_parents(close, 'c')}"
        )
    rid, draw = _quoted(RID), _quoted("__draw")
    return (
        f"{_candidates(plan, dialect, close, child_tables)} SELECT {cols} FROM cand AS c "
        f"JOIN pick ON c.{rid} = pick.{rid} AND c.{draw} = pick.{draw} "
        f"WHERE {_kept_by_parents(close, 'c')}"
    )


def closeness_counts_sql(plan: TablePlan, dialect: str, close: Closeness) -> str:
    """For the report: the rows drawn again, dropped as too near, and dropped with a parent."""
    if not close.columns:
        return (
            f"SELECT 0 AS redrawn, 0 AS dropped, COALESCE(SUM(CASE WHEN "
            f"{_kept_by_parents(close, 'c')} THEN 0 ELSE 1 END), 0) AS cascaded "
            f"FROM ({generation_sql(plan, dialect)}) AS c"
        )
    rid, draw = _quoted(RID), _quoted("__draw")
    return (
        f"{_candidates(plan, dialect, close, None)} SELECT "
        f"COALESCE(SUM(CASE WHEN pick.{draw} > 0 THEN 1 ELSE 0 END), 0) AS redrawn, "
        f"COALESCE(SUM(CASE WHEN pick.{rid} IS NULL THEN 1 ELSE 0 END), 0) AS dropped, "
        f"COALESCE(SUM(CASE WHEN pick.{rid} IS NOT NULL AND NOT ({_kept_by_parents(close, 'c')}) "
        f"THEN 1 ELSE 0 END), 0) AS cascaded "
        f"FROM cand AS c0 LEFT JOIN pick ON c0.{rid} = pick.{rid} "
        f"LEFT JOIN cand AS c ON c.{rid} = pick.{rid} AND c.{draw} = pick.{draw} "
        f"WHERE c0.{draw} = 0"
    )


def _two_nearest(pairs: str, a_id: str, distance: str) -> str:
    """Each row's nearest and second nearest distance over ``pairs``."""
    return (
        f"SELECT a_id, MAX(CASE WHEN k = 1 THEN dist END) AS nn1, "
        f"MAX(CASE WHEN k = 2 THEN dist END) AS nn2 FROM (SELECT {a_id} AS a_id, {distance} AS "
        f"dist, row_number() OVER (PARTITION BY {a_id} ORDER BY {distance}) AS k FROM {pairs}) "
        f"AS r WHERE k <= 2 GROUP BY a_id"
    )


def sample_nearest_sql(close: Closeness) -> str:
    """Each real sample row's nearest and second nearest other real row (the same in every
    dialect)."""
    sid = _quoted(SAMPLE_ID)
    return _two_nearest(
        f"{close.sample} AS a JOIN {close.sample} AS b ON a.{sid} <> b.{sid}",
        f"a.{sid}",
        _distance(close.columns, "a", "b"),
    )


def generated_nearest_sql(
    plan: TablePlan, dialect: str, close: Closeness, table: str, limit: int, seed: int
) -> str:
    """Up to ``limit`` generated rows of ``table`` (its engine address), chosen by a draw of
    their values, each with its nearest and second nearest real sample row."""
    d = _Dialect(dialect)
    values = ", ".join(
        f"{comparable(d, c, 'x.' + _quoted(c.name))} AS {_quoted(f'__d{i}')}"
        for i, c in enumerate(close.columns)
    )
    text = ", ".join(
        f"COALESCE(CAST({_quoted(f'__d{i}')} AS VARCHAR), '')" for i in range(len(close.columns))
    )
    order = d.uniform(seed, plan.name, "", "closeness", f"concat_ws('|', {text})")
    picked = (
        f"(SELECT row_number() OVER (ORDER BY o, {text}) AS gid, * FROM (SELECT {order} AS o, * "
        f"FROM (SELECT {values} FROM {table} AS x) AS v) AS w ORDER BY o LIMIT {limit}) AS a"
    )
    return _two_nearest(
        f"{picked} CROSS JOIN {close.sample} AS b", "a.gid", _distance(close.columns, "a", "b")
    )
