# Copyright (c) 2026 Kenneth Stott
# Canary: b2c3d4e5-f6a7-8901-bcde-f12345678901
#
# This source code is licensed under the Business Source License 1.1
# found in the LICENSE file in the root directory of this source tree.
#
# NOTICE: Use of this software for training artificial intelligence or
# machine learning models is strictly prohibited without explicit written
# permission from the copyright holder.

"""Static system-table column layouts (extracted from catalog_data.py)."""

from __future__ import annotations


_SYSTEM_TABLE_COLUMNS: dict[str, list[tuple[str, str]]] = {
    "schemata": [
        ("catalog_name", "name"),
        ("schema_name", "name"),
        ("schema_owner", "name"),
        ("default_character_set_catalog", "name"),
        ("default_character_set_schema", "name"),
        ("default_character_set_name", "name"),
        ("sql_path", "character varying"),
    ],
    "tables": [
        ("table_catalog", "name"),
        ("table_schema", "name"),
        ("table_name", "name"),
        ("table_type", "character varying"),
        ("self_referencing_column_name", "name"),
        ("reference_generation", "character varying"),
        ("user_defined_type_catalog", "name"),
        ("user_defined_type_schema", "name"),
        ("user_defined_type_name", "name"),
        ("is_insertable_into", "character varying"),
        ("is_typed", "character varying"),
        ("commit_action", "character varying"),
    ],
    "columns": [
        ("table_catalog", "name"),
        ("table_schema", "name"),
        ("table_name", "name"),
        ("column_name", "name"),
        ("ordinal_position", "integer"),
        ("column_default", "character varying"),
        ("is_nullable", "character varying"),
        ("data_type", "character varying"),
        ("character_maximum_length", "integer"),
        ("character_octet_length", "integer"),
        ("numeric_precision", "integer"),
        ("numeric_precision_radix", "integer"),
        ("numeric_scale", "integer"),
        ("datetime_precision", "integer"),
        ("interval_type", "character varying"),
        ("interval_precision", "integer"),
        ("character_set_catalog", "name"),
        ("character_set_schema", "name"),
        ("character_set_name", "name"),
        ("collation_catalog", "name"),
        ("collation_schema", "name"),
        ("collation_name", "name"),
        ("domain_catalog", "name"),
        ("domain_schema", "name"),
        ("domain_name", "name"),
        ("udt_catalog", "name"),
        ("udt_schema", "name"),
        ("udt_name", "name"),
        ("scope_catalog", "name"),
        ("scope_schema", "name"),
        ("scope_name", "name"),
        ("maximum_cardinality", "integer"),
        ("dtd_identifier", "name"),
        ("is_self_referencing", "character varying"),
        ("is_identity", "character varying"),
        ("identity_generation", "character varying"),
        ("identity_start", "character varying"),
        ("identity_increment", "character varying"),
        ("identity_maximum", "character varying"),
        ("identity_minimum", "character varying"),
        ("identity_cycle", "character varying"),
        ("is_generated", "character varying"),
        ("generation_expression", "character varying"),
        ("is_updatable", "character varying"),
    ],
    "views": [
        ("table_catalog", "name"),
        ("table_schema", "name"),
        ("table_name", "name"),
        ("view_definition", "character varying"),
        ("check_option", "character varying"),
        ("is_updatable", "character varying"),
        ("is_insertable_into", "character varying"),
        ("is_trigger_updatable", "character varying"),
        ("is_trigger_deletable", "character varying"),
        ("is_trigger_insertable_into", "character varying"),
    ],
    "key_column_usage": [
        ("constraint_catalog", "name"),
        ("constraint_schema", "name"),
        ("constraint_name", "name"),
        ("table_catalog", "name"),
        ("table_schema", "name"),
        ("table_name", "name"),
        ("column_name", "name"),
        ("ordinal_position", "integer"),
        ("position_in_unique_constraint", "integer"),
    ],
    "table_constraints": [
        ("constraint_catalog", "name"),
        ("constraint_schema", "name"),
        ("constraint_name", "name"),
        ("table_catalog", "name"),
        ("table_schema", "name"),
        ("table_name", "name"),
        ("constraint_type", "character varying"),
        ("is_deferrable", "character varying"),
        ("initially_deferred", "character varying"),
        ("enforced", "character varying"),
        ("nulls_distinct", "character varying"),
    ],
    "referential_constraints": [
        ("constraint_catalog", "name"),
        ("constraint_schema", "name"),
        ("constraint_name", "name"),
        ("unique_constraint_catalog", "name"),
        ("unique_constraint_schema", "name"),
        ("unique_constraint_name", "name"),
        ("match_option", "character varying"),
        ("update_rule", "character varying"),
        ("delete_rule", "character varying"),
    ],
    "role_table_grants": [
        ("grantor", "name"),
        ("grantee", "name"),
        ("table_catalog", "name"),
        ("table_schema", "name"),
        ("table_name", "name"),
        ("privilege_type", "character varying"),
        ("is_grantable", "character varying"),
        ("with_hierarchy", "character varying"),
    ],
    "role_column_grants": [
        ("grantor", "name"),
        ("grantee", "name"),
        ("table_catalog", "name"),
        ("table_schema", "name"),
        ("table_name", "name"),
        ("column_name", "name"),
        ("privilege_type", "character varying"),
        ("is_grantable", "character varying"),
    ],
    "triggers": [
        ("trigger_catalog", "name"),
        ("trigger_schema", "name"),
        ("trigger_name", "name"),
        ("event_manipulation", "character varying"),
        ("event_object_catalog", "name"),
        ("event_object_schema", "name"),
        ("event_object_table", "name"),
        ("action_order", "integer"),
        ("action_condition", "character varying"),
        ("action_statement", "character varying"),
        ("action_orientation", "character varying"),
        ("action_timing", "character varying"),
        ("action_reference_old_table", "name"),
        ("action_reference_new_table", "name"),
        ("action_reference_old_row", "name"),
        ("action_reference_new_row", "name"),
        ("created", "timestamp with time zone"),
    ],
    "sequences": [
        ("sequence_catalog", "name"),
        ("sequence_schema", "name"),
        ("sequence_name", "name"),
        ("data_type", "character varying"),
        ("numeric_precision", "integer"),
        ("numeric_precision_radix", "integer"),
        ("numeric_scale", "integer"),
        ("start_value", "character varying"),
        ("minimum_value", "character varying"),
        ("maximum_value", "character varying"),
        ("increment", "character varying"),
        ("cycle_option", "character varying"),
    ],
    "routines": [
        ("specific_catalog", "name"),
        ("specific_schema", "name"),
        ("specific_name", "name"),
        ("routine_catalog", "name"),
        ("routine_schema", "name"),
        ("routine_name", "name"),
        ("routine_type", "character varying"),
        ("data_type", "character varying"),
        ("numeric_precision", "integer"),
        ("numeric_precision_radix", "integer"),
        ("numeric_scale", "integer"),
        ("datetime_precision", "integer"),
        ("routine_body", "character varying"),
        ("routine_definition", "character varying"),
        ("external_name", "character varying"),
        ("external_language", "character varying"),
        ("parameter_style", "character varying"),
        ("is_deterministic", "character varying"),
        ("sql_data_access", "character varying"),
        ("security_type", "character varying"),
        ("created", "timestamp with time zone"),
        ("last_altered", "timestamp with time zone"),
    ],
    "parameters": [
        ("specific_catalog", "name"),
        ("specific_schema", "name"),
        ("specific_name", "name"),
        ("ordinal_position", "integer"),
        ("parameter_mode", "character varying"),
        ("is_result", "character varying"),
        ("as_locator", "character varying"),
        ("parameter_name", "name"),
        ("data_type", "character varying"),
        ("character_maximum_length", "integer"),
        ("character_octet_length", "integer"),
        ("numeric_precision", "integer"),
        ("numeric_precision_radix", "integer"),
        ("numeric_scale", "integer"),
        ("datetime_precision", "integer"),
        ("interval_type", "character varying"),
        ("interval_precision", "integer"),
        ("udt_catalog", "name"),
        ("udt_schema", "name"),
        ("udt_name", "name"),
        ("dtd_identifier", "name"),
        ("parameter_default", "character varying"),
    ],
    "enabled_roles": [("role_name", "name")],
    "applicable_roles": [
        ("grantee", "name"),
        ("role_name", "name"),
        ("is_grantable", "character varying"),
    ],
    "pg_namespace": [
        ("oid", "oid"),
        ("nspname", "name"),
        ("nspowner", "oid"),
        ("nspacl", "ARRAY"),
    ],
    "pg_class": [
        ("oid", "oid"),
        ("relname", "name"),
        ("relnamespace", "oid"),
        ("reltype", "oid"),
        ("reloftype", "oid"),
        ("relowner", "oid"),
        ("relam", "oid"),
        ("relfilenode", "oid"),
        ("reltablespace", "oid"),
        ("relpages", "integer"),
        ("reltuples", "real"),
        ("relallvisible", "integer"),
        ("reltoastrelid", "oid"),
        ("relhasindex", "boolean"),
        ("relisshared", "boolean"),
        ("relpersistence", "char"),
        ("relkind", "char"),
        ("relnatts", "smallint"),
        ("relchecks", "smallint"),
        ("relhasrules", "boolean"),
        ("relhastriggers", "boolean"),
        ("relhassubclass", "boolean"),
        ("relrowsecurity", "boolean"),
        ("relforcerowsecurity", "boolean"),
        ("relispopulated", "boolean"),
        ("relreplident", "char"),
        ("relispartition", "boolean"),
        ("relrewrite", "oid"),
        ("relfrozenxid", "xid"),
        ("relminmxid", "xid"),
        ("relacl", "ARRAY"),
        ("reloptions", "ARRAY"),
        ("relpartbound", "text"),
    ],
    "pg_attribute": [
        ("attrelid", "oid"),
        ("attname", "name"),
        ("atttypid", "oid"),
        ("attlen", "smallint"),
        ("attnum", "smallint"),
        ("attcacheoff", "integer"),
        ("atttypmod", "integer"),
        ("attndims", "smallint"),
        ("attbyval", "boolean"),
        ("attalign", "char"),
        ("attstorage", "char"),
        ("attnotnull", "boolean"),
        ("atthasdef", "boolean"),
        ("atthasmissing", "boolean"),
        ("attidentity", "char"),
        ("attgenerated", "char"),
        ("attisdropped", "boolean"),
        ("attislocal", "boolean"),
        ("attinhcount", "smallint"),
        ("attstattarget", "smallint"),
        ("attcollation", "oid"),
        ("attacl", "ARRAY"),
        ("attoptions", "ARRAY"),
        ("attfdwoptions", "ARRAY"),
    ],
    "pg_type": [
        ("oid", "oid"),
        ("typname", "name"),
        ("typnamespace", "oid"),
        ("typowner", "oid"),
        ("typlen", "smallint"),
        ("typbyval", "boolean"),
        ("typtype", "char"),
        ("typcategory", "char"),
        ("typispreferred", "boolean"),
        ("typisdefined", "boolean"),
        ("typdelim", "char"),
        ("typrelid", "oid"),
        ("typelem", "oid"),
        ("typarray", "oid"),
        ("typinput", "integer"),
        ("typoutput", "integer"),
        ("typreceive", "integer"),
        ("typsend", "integer"),
        ("typmodin", "integer"),
        ("typmodout", "integer"),
        ("typanalyze", "integer"),
        ("typalign", "char"),
        ("typstorage", "char"),
        ("typnotnull", "boolean"),
        ("typbasetype", "oid"),
        ("typtypmod", "integer"),
        ("typndims", "integer"),
        ("typcollation", "oid"),
        ("typdefaultbin", "text"),
        ("typdefault", "text"),
        ("typacl", "ARRAY"),
    ],
    "pg_attrdef": [
        ("oid", "oid"),
        ("adrelid", "oid"),
        ("adnum", "smallint"),
        ("adbin", "text"),
    ],
    "pg_description": [
        ("objoid", "oid"),
        ("classoid", "oid"),
        ("objsubid", "integer"),
        ("description", "text"),
    ],
    "pg_index": [
        ("indexrelid", "oid"),
        ("indrelid", "oid"),
        ("indnatts", "smallint"),
        ("indnkeyatts", "smallint"),
        ("indisunique", "boolean"),
        ("indisprimary", "boolean"),
        ("indisexclusion", "boolean"),
        ("indimmediate", "boolean"),
        ("indisclustered", "boolean"),
        ("indisvalid", "boolean"),
        ("indisready", "boolean"),
        ("indislive", "boolean"),
        ("indkey", "ARRAY"),
        ("indexprs", "text"),
        ("indpred", "text"),
    ],
    "pg_constraint": [
        ("oid", "oid"),
        ("conname", "name"),
        ("connamespace", "oid"),
        ("contype", "char"),
        ("condeferrable", "boolean"),
        ("condeferred", "boolean"),
        ("convalidated", "boolean"),
        ("conrelid", "oid"),
        ("contypid", "oid"),
        ("conindid", "oid"),
        ("conparentid", "oid"),
        ("confrelid", "oid"),
        ("confupdtype", "char"),
        ("confdeltype", "char"),
        ("confmatchtype", "char"),
        ("conislocal", "boolean"),
        ("coninhcount", "smallint"),
        ("connoinherit", "boolean"),
        ("conkey", "ARRAY"),
        ("confkey", "ARRAY"),
        ("conpfeqop", "ARRAY"),
        ("conppeqop", "ARRAY"),
        ("conffeqop", "ARRAY"),
        ("conexclop", "ARRAY"),
        ("conbin", "text"),
    ],
    "pg_proc": [
        ("oid", "oid"),
        ("proname", "name"),
        ("pronamespace", "oid"),
        ("proowner", "oid"),
        ("prolang", "oid"),
        ("procost", "real"),
        ("prorows", "real"),
        ("provariadic", "oid"),
        ("prokind", "char"),
        ("prosecdef", "boolean"),
        ("proisstrict", "boolean"),
        ("proretset", "boolean"),
        ("provolatile", "char"),
        ("proparallel", "char"),
        ("pronargs", "smallint"),
        ("pronargdefaults", "smallint"),
        ("prorettype", "oid"),
        ("proargtypes", "ARRAY"),
        ("proallargtypes", "ARRAY"),
        ("proargmodes", "ARRAY"),
        ("proargnames", "ARRAY"),
        ("prosrc", "text"),
        ("probin", "text"),
        ("proacl", "ARRAY"),
    ],
    "pg_roles": [
        ("rolname", "name"),
        ("rolsuper", "boolean"),
        ("rolinherit", "boolean"),
        ("rolcreaterole", "boolean"),
        ("rolcreatedb", "boolean"),
        ("rolcanlogin", "boolean"),
        ("rolreplication", "boolean"),
        ("rolconnlimit", "integer"),
        ("rolpassword", "text"),
        ("rolvaliduntil", "timestamp with time zone"),
        ("rolbypassrls", "boolean"),
        ("rolconfig", "ARRAY"),
        ("oid", "oid"),
    ],
    "pg_auth_members": [
        ("oid", "oid"),
        ("roleid", "oid"),
        ("member", "oid"),
        ("grantor", "oid"),
        ("admin_option", "boolean"),
        ("inherit_option", "boolean"),
        ("set_option", "boolean"),
    ],
    "pg_database": [
        ("oid", "oid"),
        ("datname", "name"),
        ("datdba", "oid"),
        ("encoding", "integer"),
        ("datistemplate", "boolean"),
        ("datallowconn", "boolean"),
        ("datconnlimit", "integer"),
        ("datfrozenxid", "xid"),
        ("datminmxid", "xid"),
        ("dattablespace", "oid"),
        ("datcollate", "text"),
        ("datctype", "text"),
        ("datacl", "ARRAY"),
    ],
    "pg_settings": [
        ("name", "text"),
        ("setting", "text"),
        ("unit", "text"),
        ("category", "text"),
        ("short_desc", "text"),
        ("extra_desc", "text"),
        ("context", "text"),
        ("vartype", "text"),
        ("source", "text"),
        ("min_val", "text"),
        ("max_val", "text"),
        ("enumvals", "ARRAY"),
        ("boot_val", "text"),
        ("reset_val", "text"),
        ("sourcefile", "text"),
        ("sourceline", "integer"),
        ("pending_restart", "boolean"),
    ],
    "pg_tables": [
        ("schemaname", "name"),
        ("tablename", "name"),
        ("tableowner", "name"),
        ("tablespace", "name"),
        ("hasindexes", "boolean"),
        ("hasrules", "boolean"),
        ("hastriggers", "boolean"),
        ("rowsecurity", "boolean"),
    ],
    "pg_stat_user_tables": [
        ("relid", "oid"),
        ("schemaname", "name"),
        ("relname", "name"),
        ("seq_scan", "bigint"),
        ("seq_tup_read", "bigint"),
        ("idx_scan", "bigint"),
        ("idx_tup_fetch", "bigint"),
        ("n_tup_ins", "bigint"),
        ("n_tup_upd", "bigint"),
        ("n_tup_del", "bigint"),
        ("n_tup_hot_upd", "bigint"),
        ("n_live_tup", "bigint"),
        ("n_dead_tup", "bigint"),
        ("n_mod_since_analyze", "bigint"),
        ("last_vacuum", "timestamp with time zone"),
        ("last_autovacuum", "timestamp with time zone"),
        ("last_analyze", "timestamp with time zone"),
        ("last_autoanalyze", "timestamp with time zone"),
        ("vacuum_count", "bigint"),
        ("autovacuum_count", "bigint"),
        ("analyze_count", "bigint"),
        ("autoanalyze_count", "bigint"),
    ],
    "pg_statio_user_tables": [
        ("relid", "oid"),
        ("schemaname", "name"),
        ("relname", "name"),
        ("heap_blks_read", "bigint"),
        ("heap_blks_hit", "bigint"),
        ("idx_blks_read", "bigint"),
        ("idx_blks_hit", "bigint"),
        ("toast_blks_read", "bigint"),
        ("toast_blks_hit", "bigint"),
        ("tidx_blks_read", "bigint"),
        ("tidx_blks_hit", "bigint"),
    ],
    "pg_am": [
        ("oid", "oid"),
        ("amname", "name"),
        ("amhandler", "integer"),
        ("amtype", "char"),
    ],
    "pg_tablespace": [
        ("oid", "oid"),
        ("spcname", "name"),
        ("spcowner", "oid"),
        ("spcacl", "ARRAY"),
        ("spcoptions", "ARRAY"),
    ],
    "pg_extension": [
        ("oid", "oid"),
        ("extname", "name"),
        ("extowner", "oid"),
        ("extnamespace", "oid"),
        ("extrelocatable", "boolean"),
        ("extversion", "text"),
        ("extconfig", "ARRAY"),
        ("extcondition", "ARRAY"),
    ],
    "pg_enum": [
        ("oid", "oid"),
        ("enumtypid", "oid"),
        ("enumsortorder", "real"),
        ("enumlabel", "name"),
    ],
    "pg_trigger": [
        ("oid", "oid"),
        ("tgrelid", "oid"),
        ("tgparentid", "oid"),
        ("tgname", "name"),
        ("tgfoid", "oid"),
        ("tgtype", "smallint"),
        ("tgenabled", "char"),
        ("tgisinternal", "boolean"),
        ("tgconstrrelid", "oid"),
        ("tgconstrindid", "oid"),
        ("tgconstraint", "oid"),
        ("tgdeferrable", "boolean"),
        ("tginitdeferred", "boolean"),
        ("tgnargs", "smallint"),
        ("tgattr", "ARRAY"),
        ("tgargs", "text"),
        ("tgqual", "text"),
        ("tgoldtable", "name"),
        ("tgnewtable", "name"),
    ],
    "pg_inherits": [
        ("inhrelid", "oid"),
        ("inhparent", "oid"),
        ("inhseqno", "integer"),
    ],
    "pg_depend": [
        ("classid", "oid"),
        ("objid", "oid"),
        ("objsubid", "integer"),
        ("refclassid", "oid"),
        ("refobjid", "oid"),
        ("refobjsubid", "integer"),
        ("deptype", "char"),
    ],
    "pg_aggregate": [
        ("aggfnoid", "integer"),
        ("aggkind", "char"),
        ("aggnumdirectargs", "smallint"),
        ("aggtransfn", "integer"),
        ("aggfinalfn", "integer"),
        ("aggsortop", "oid"),
        ("aggtranstype", "oid"),
        ("aggtransspace", "integer"),
        ("agginitval", "text"),
    ],
    "pg_language": [
        ("oid", "oid"),
        ("lanname", "name"),
        ("lanowner", "oid"),
        ("lanispl", "boolean"),
        ("lanpltrusted", "boolean"),
        ("lanplcallfoid", "oid"),
        ("laninline", "oid"),
        ("lanvalidator", "oid"),
        ("lanacl", "ARRAY"),
    ],
    "pg_operator": [
        ("oid", "oid"),
        ("oprname", "name"),
        ("oprnamespace", "oid"),
        ("oprowner", "oid"),
        ("oprkind", "char"),
        ("oprcanmerge", "boolean"),
        ("oprcanhash", "boolean"),
        ("oprleft", "oid"),
        ("oprright", "oid"),
        ("oprresult", "oid"),
        ("oprcom", "oid"),
        ("oprnegate", "oid"),
        ("oprcode", "integer"),
        ("oprrest", "integer"),
        ("oprjoin", "integer"),
    ],
    "pg_cast": [
        ("oid", "oid"),
        ("castsource", "oid"),
        ("casttarget", "oid"),
        ("castfunc", "oid"),
        ("castcontext", "char"),
        ("castmethod", "char"),
    ],
    "pg_collation": [
        ("oid", "oid"),
        ("collname", "name"),
        ("collnamespace", "oid"),
        ("collowner", "oid"),
        ("collprovider", "char"),
        ("collisdeterministic", "boolean"),
        ("collencoding", "integer"),
        ("collcollate", "text"),
        ("collctype", "text"),
    ],
    "pg_range": [
        ("rngtypid", "oid"),
        ("rngsubtype", "oid"),
        ("rngcollation", "oid"),
        ("rngsubopc", "oid"),
        ("rngcanonical", "integer"),
        ("rngsubdiff", "integer"),
    ],
    "pg_foreign_table": [
        ("ftrelid", "oid"),
        ("ftserver", "oid"),
        ("ftoptions", "ARRAY"),
    ],
    "pg_foreign_server": [
        ("oid", "oid"),
        ("srvname", "name"),
        ("srvowner", "oid"),
        ("srvfdw", "oid"),
        ("srvtype", "text"),
        ("srvversion", "text"),
        ("srvacl", "ARRAY"),
        ("srvoptions", "ARRAY"),
    ],
    "pg_sequence": [
        ("seqrelid", "oid"),
        ("seqtypid", "oid"),
        ("seqstart", "bigint"),
        ("seqincrement", "bigint"),
        ("seqmax", "bigint"),
        ("seqmin", "bigint"),
        ("seqcache", "bigint"),
        ("seqcycle", "boolean"),
    ],
    "pg_locks": [
        ("locktype", "text"),
        ("database", "oid"),
        ("relation", "oid"),
        ("page", "integer"),
        ("tuple", "smallint"),
        ("virtualxid", "text"),
        ("transactionid", "xid"),
        ("classid", "oid"),
        ("objid", "oid"),
        ("objsubid", "smallint"),
        ("virtualtransaction", "text"),
        ("pid", "integer"),
        ("mode", "text"),
        ("granted", "boolean"),
        ("fastpath", "boolean"),
        ("waitstart", "timestamp with time zone"),
    ],
    "pg_shdescription": [
        ("objoid", "oid"),
        ("classoid", "oid"),
        ("description", "text"),
    ],
    "pg_conversion": [
        ("oid", "oid"),
        ("conname", "name"),
        ("connamespace", "oid"),
        ("conowner", "oid"),
        ("conforencoding", "integer"),
        ("contoencoding", "integer"),
        ("conproc", "integer"),
        ("condefault", "boolean"),
    ],
    "pg_stat_activity": [
        ("datid", "oid"),
        ("datname", "name"),
        ("pid", "integer"),
        ("leader_pid", "integer"),
        ("usesysid", "oid"),
        ("usename", "name"),
        ("application_name", "text"),
        ("client_addr", "text"),
        ("client_hostname", "text"),
        ("client_port", "integer"),
        ("backend_start", "timestamp with time zone"),
        ("xact_start", "timestamp with time zone"),
        ("query_start", "timestamp with time zone"),
        ("state_change", "timestamp with time zone"),
        ("wait_event_type", "text"),
        ("wait_event", "text"),
        ("state", "text"),
        ("backend_xid", "xid"),
        ("backend_xmin", "xid"),
        ("query_id", "bigint"),
        ("query", "text"),
        ("backend_type", "text"),
    ],
    "pg_rewrite": [
        ("oid", "oid"),
        ("rulename", "name"),
        ("ev_class", "oid"),
        ("ev_type", "char"),
        ("ev_enabled", "char"),
        ("is_instead", "boolean"),
        ("ev_qual", "text"),
        ("ev_action", "text"),
    ],
    "pg_shdepend": [
        ("dbid", "oid"),
        ("classid", "oid"),
        ("objid", "oid"),
        ("objsubid", "integer"),
        ("refclassid", "oid"),
        ("refobjid", "oid"),
        ("deptype", "char"),
    ],
    "pg_partitioned_table": [
        ("partrelid", "oid"),
        ("partstrat", "char"),
        ("partnatts", "smallint"),
        ("partdefid", "oid"),
        ("partattrs", "ARRAY"),
        ("partclass", "ARRAY"),
        ("partcollation", "ARRAY"),
        ("partexprs", "text"),
    ],
    "pg_publication": [
        ("oid", "oid"),
        ("pubname", "name"),
        ("pubowner", "oid"),
        ("puballtables", "boolean"),
        ("pubinsert", "boolean"),
        ("pubupdate", "boolean"),
        ("pubdelete", "boolean"),
        ("pubtruncate", "boolean"),
        ("pubviaroot", "boolean"),
    ],
    "pg_subscription": [
        ("oid", "oid"),
        ("subdbid", "oid"),
        ("subskiplsn", "text"),
        ("subname", "name"),
        ("subowner", "oid"),
        ("subenabled", "boolean"),
        ("subbinary", "boolean"),
        ("substream", "char"),
        ("subtwophasestate", "char"),
        ("subdisableonerr", "boolean"),
        ("subconninfo", "text"),
        ("subslotname", "name"),
        ("subsynccommit", "text"),
        ("subpublications", "ARRAY"),
    ],
    "pg_event_trigger": [
        ("oid", "oid"),
        ("evtname", "name"),
        ("evtevent", "name"),
        ("evtowner", "oid"),
        ("evtfoid", "oid"),
        ("evtenabled", "char"),
        ("evttags", "ARRAY"),
    ],
    "pg_stat_user_indexes": [
        ("relid", "oid"),
        ("indexrelid", "oid"),
        ("schemaname", "name"),
        ("relname", "name"),
        ("indexrelname", "name"),
        ("idx_scan", "bigint"),
        ("last_idx_scan", "timestamp with time zone"),
        ("idx_tup_read", "bigint"),
        ("idx_tup_fetch", "bigint"),
    ],
    "pg_user_mapping": [
        ("oid", "oid"),
        ("umuser", "oid"),
        ("umserver", "oid"),
        ("umoptions", "ARRAY"),
    ],
    "pg_foreign_data_wrapper": [
        ("oid", "oid"),
        ("fdwname", "name"),
        ("fdwowner", "oid"),
        ("fdwhandler", "oid"),
        ("fdwvalidator", "oid"),
        ("fdwacl", "ARRAY"),
        ("fdwoptions", "ARRAY"),
    ],
    "pg_policy": [
        ("oid", "oid"),
        ("polname", "name"),
        ("polrelid", "oid"),
        ("polcmd", "char"),
        ("polpermissive", "boolean"),
        ("polroles", "ARRAY"),
        ("polqual", "text"),
        ("polwithcheck", "text"),
    ],
}
