coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery.uri=http://localhost:8080
catalog.management=dynamic
query.max-memory=1GB
query.max-memory-per-node=512MB
query.max-total-memory=2GB
