apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-provisa
spec:
  selector:
    app: provisa
  ports:
    - name: http
      port: {{ .Values.provisa.port }}
      targetPort: {{ .Values.provisa.port }}
      protocol: TCP
    - name: flight
      port: {{ .Values.provisa.flightPort }}
      targetPort: {{ .Values.provisa.flightPort }}
      protocol: TCP
  type: ClusterIP
