apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  pg-password: "{{ .Values.postgresql.password }}"
  minio-access-key: "{{ .Values.minio.accessKey }}"
  minio-secret-key: "{{ .Values.minio.secretKey }}"
  grafana-admin-password: "{{ .Values.observability.grafana.adminPassword }}"
  trino-pg-password: "{{ .Values.postgresql.password }}"
  redis-password: "{{ .Values.redis.password }}"
