{{- if .Values.trino.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-trino-config
data:
  coordinator-config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port={{ .Values.trino.port }}
    discovery.uri=http://{{ .Release.Name }}-trino-coordinator:{{ .Values.trino.port }}
  worker-config.properties: |
    coordinator=false
    http-server.http.port={{ .Values.trino.port }}
    discovery.uri=http://{{ .Release.Name }}-trino-coordinator:{{ .Values.trino.port }}
  {{- if .Values.mongodb.enabled }}
  reviews_mongo.properties: |
    connector.name=mongodb
    mongodb.connection-url=mongodb://{{ .Release.Name }}-mongodb:{{ .Values.mongodb.port }}/
    mongodb.schema-collection=_schema
  {{- end }}
{{- end }}
