# First-launch setup for Windows installer.
# Loads bundled Docker images and writes Provisa config.
#Requires -Version 5.1
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$ScriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Path
$ImagesDir   = Join-Path $ScriptDir 'images'
$ComposeDir  = Join-Path $ScriptDir 'compose'
$ProvisaHome = Join-Path $env:USERPROFILE '.provisa'
$Sentinel    = Join-Path $ProvisaHome '.first-launch-complete'

function Write-Info  { param($Msg) Write-Host "[provisa] $Msg" -ForegroundColor Cyan }
function Write-Ok    { param($Msg) Write-Host "[provisa] $Msg" -ForegroundColor Green }
function Write-Err   { param($Msg) Write-Host "[provisa] $Msg" -ForegroundColor Red }

# ── Check Docker ───────────────────────────────────────────────────────────────
function Check-Docker {
  $result = docker info 2>&1
  if ($LASTEXITCODE -ne 0) {
    Write-Err 'Docker Desktop is not running. Start Docker Desktop and re-run.'
    exit 1
  }
  Write-Ok 'Docker Desktop is running.'
}

# ── Load images ────────────────────────────────────────────────────────────────
function Load-Images {
  Write-Info 'Loading bundled container images (no network required)...'
  $tars = Get-ChildItem -Path $ImagesDir -Filter '*.tar' -ErrorAction Stop
  foreach ($tar in $tars) {
    Write-Info "  Loading: $($tar.Name)"
    docker load -i $tar.FullName
    if ($LASTEXITCODE -ne 0) {
      Write-Err "Failed to load image: $($tar.Name)"
      exit 1
    }
  }
  Write-Ok "Loaded $($tars.Count) images."
}

# ── Write config ───────────────────────────────────────────────────────────────
function Write-Config {
  if (-not (Test-Path $ProvisaHome)) {
    New-Item -ItemType Directory -Path $ProvisaHome -Force | Out-Null
  }
  $configPath = Join-Path $ProvisaHome 'config.yaml'
  if (Test-Path $configPath) { return }

  $composeDirFwd = $ComposeDir -replace '\\', '/'
  $content = @"
# Provisa configuration — generated by Windows installer
project_dir: "$composeDirFwd"
ui_port: 3000
api_port: 8000
auto_open_browser: true
runtime: docker
"@
  Set-Content -Path $configPath -Value $content -Encoding UTF8
  Write-Ok "Config written to $configPath"
}

# ── Main ───────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "Provisa — First Launch Setup" -ForegroundColor White
Write-Host "===========================================" -ForegroundColor White
Write-Host ""
Write-Info 'Setting up Provisa (no internet required)...'

Check-Docker
Load-Images
Write-Config

if (-not (Test-Path $ProvisaHome)) {
  New-Item -ItemType Directory -Path $ProvisaHome -Force | Out-Null
}
New-Item -ItemType File -Path $Sentinel -Force | Out-Null

Write-Ok 'First-launch setup complete.'
Write-Host ""
Write-Host 'Provisa is ready.' -ForegroundColor Green
Write-Host 'Run: provisa start' -ForegroundColor White
Write-Host ""
