# Provisa first-launch (native tier, REQ-979) for Windows. Stages the bundled
# standalone Python runtime to %USERPROFILE%\.provisa\runtime, writes config, and
# starts the app. No Docker, no VirtualBox, no containers. Mirrors the native path
# in macOS first-launch.sh (stage_native_runtime + write_config).
#Requires -Version 5.1
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$ScriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProvisaHome = Join-Path $env:USERPROFILE '.provisa'
$ConfigPath  = Join-Path $ProvisaHome 'config.yaml'
$RuntimeSrc  = Join-Path $ScriptDir 'runtime'
$RuntimeDst  = Join-Path $ProvisaHome 'runtime'
$Sentinel    = Join-Path $ProvisaHome '.setup-complete'

function Write-Info { param($Msg) Write-Host "[provisa] $Msg" -ForegroundColor Cyan }
function Write-Err  { param($Msg) Write-Host "[provisa] $Msg" -ForegroundColor Red }
function Write-Ok   { param($Msg) Write-Host "[provisa] $Msg" -ForegroundColor Green }

New-Item -ItemType Directory -Path $ProvisaHome -Force | Out-Null

# ── Stage the native runtime ──────────────────────────────────────────────────
function Stage-Runtime {
  if (Test-Path (Join-Path $RuntimeDst 'python.exe')) { return }
  if (-not (Test-Path (Join-Path $RuntimeSrc 'python.exe'))) {
    Write-Err "Native runtime not found beside the installer. This installer was not built with the native tier."
    exit 1
  }
  Write-Info "Staging native runtime to $RuntimeDst..."
  Copy-Item -Path $RuntimeSrc -Destination $RuntimeDst -Recurse -Force
  Write-Ok 'Native runtime staged.'
}

# ── Write config (native tier) ────────────────────────────────────────────────
function Write-ProvisaConfig {
  if (Test-Path $ConfigPath) { return }
  $hostname = if ($env:PROVISA_HOSTNAME)  { $env:PROVISA_HOSTNAME }  else { 'localhost' }
  $uiPort   = if ($env:PROVISA_UI_PORT)   { $env:PROVISA_UI_PORT }   else { '3000' }
  $apiPort  = if ($env:PROVISA_API_PORT)  { $env:PROVISA_API_PORT }  else { '8000' }
  $engine   = if ($env:PROVISA_ENGINE)    { $env:PROVISA_ENGINE }    else { 'duckdb' }
  @"
# Provisa configuration — generated by installer (native tier)
hostname: $hostname
ui_port: $uiPort
api_port: $apiPort
auto_open_browser: true
runtime: native
# Deployment (REQ-972..979): the CLI starts the app with this engine env.
engine: $engine
engine_url: ""
demo: false
"@ | Set-Content -Path $ConfigPath -Encoding UTF8
  Write-Ok "Config written to $ConfigPath"
}

# ── Main ──────────────────────────────────────────────────────────────────────
Write-Host ''
Write-Host 'Provisa — First Launch Setup (native — no Docker)' -ForegroundColor White
Write-Host '═══════════════════════════════════════════════════'
Write-Host ''

Stage-Runtime
Write-ProvisaConfig
New-Item -ItemType File -Path $Sentinel -Force | Out-Null
Write-Ok 'First-launch setup complete.'

# Hand off to the native CLI to start + open the UI.
& powershell.exe -ExecutionPolicy Bypass -File (Join-Path $ScriptDir 'provisa-native.ps1') start
