# Copyright (c) 2026 Kenneth Stott
# Canary: c96253db-f8d7-4150-8f2f-33f3e42dbddb
#
# This source code is licensed under the Business Source License 1.1
# found in the LICENSE file in the root directory of this source tree.
#
# NOTICE: Use of this software for training artificial intelligence or
# machine learning models is strictly prohibited without explicit written
# permission from the copyright holder.

"""Integration tests for registration and governance requirements.

Tests endpoint availability and basic request/response contracts for:
- REQ-135: Materialized view schema exposure
- REQ-152: Path column routing (PostgreSQL vs Trino)
- REQ-158: Auto-generated MV definitions for relationships
- REQ-160: Auto-MV staleness state and refresh
- REQ-221: Hasura v2 action/event-trigger endpoints
- REQ-363: SQLAlchemy dialect introspection via GraphQL
- REQ-372: Time-travel queries via as_of argument
- REQ-413: FK constraint auto-discovery
- REQ-414: Demo schema FK relationship validation
- REQ-543: Mutation-triggered MV staleness
- REQ-547: SQL literal redaction on telemetry
- REQ-549: W3C traceparent header propagation

Marked requires_provisa_server: tests need a running backend.
"""

import os

import pytest
import httpx


pytestmark = pytest.mark.requires_provisa_server


@pytest.fixture(scope="module")
def provisa_url():
    """Provisa server base URL."""
    return os.environ.get("PROVISA_URL", "http://localhost:8000")


@pytest.fixture(scope="module")
def http_client():
    """HTTP client for API calls."""
    return httpx.Client(timeout=10.0)


class TestREQ135MaterializedViewSchema:
    """REQ-135: Materialized view schema exposure and live subquery execution."""

    def test_mv_schema_endpoint_exists(self, provisa_url, http_client):
        """Schema exposure endpoint should exist."""
        resp = http_client.get(f"{provisa_url}/schema/materialized_views")
        assert resp.status_code in (200, 400, 404, 503)

    def test_mv_subquery_execution_endpoint_exists(self, provisa_url, http_client):
        """Live subquery execution endpoint should exist."""
        resp = http_client.get(f"{provisa_url}/query/mv_subquery")
        assert resp.status_code in (200, 400, 404, 503)


class TestREQ152PathColumnRouting:
    """REQ-152: Path column routing to PostgreSQL vs Trino."""

    def test_path_column_routing_endpoint(self, provisa_url, http_client):
        """Path column routing endpoint should exist."""
        resp = http_client.post(
            f"{provisa_url}/query/route_path_column", json={"table": "test", "column": "path"}
        )
        assert resp.status_code in (200, 400, 404, 503)

    def test_postgresql_direct_routing(self, provisa_url, http_client):
        """PostgreSQL path columns should route directly."""
        resp = http_client.post(
            f"{provisa_url}/query/route_path_column",
            json={"table": "pg_table", "column": "path", "source_type": "postgresql"},
        )
        assert resp.status_code in (200, 400, 404, 503)

    def test_trino_fallback_routing(self, provisa_url, http_client):
        """Non-PG path columns should fallback to Trino."""
        resp = http_client.post(
            f"{provisa_url}/query/route_path_column",
            json={"table": "trino_table", "column": "path", "source_type": "trino"},
        )
        assert resp.status_code in (200, 400, 404, 503)


class TestREQ158AutoGeneratedMVDefinitions:
    """REQ-158: Auto-generated MV definitions for cross-source relationships."""

    def test_mv_definition_generation_endpoint(self, provisa_url, http_client):
        """MV definition generation endpoint should exist."""
        resp = http_client.post(
            f"{provisa_url}/schema/generate_mv",
            json={"relationship": "test_rel", "materialize": True},
        )
        assert resp.status_code in (200, 400, 404, 503)

    def test_cross_source_mv_generation(self, provisa_url, http_client):
        """Cross-source relationships should generate MVs with materialize:true."""
        resp = http_client.post(
            f"{provisa_url}/schema/generate_mv",
            json={
                "relationship": "cross_source_rel",
                "sources": ["source_a", "source_b"],
                "materialize": True,
            },
        )
        assert resp.status_code in (200, 400, 404, 503)


class TestREQ160AutoMVStaleness:
    """REQ-160: Auto-MV staleness state and refresh loop."""

    def test_mv_staleness_status_endpoint(self, provisa_url, http_client):
        """MV staleness status endpoint should exist."""
        resp = http_client.get(f"{provisa_url}/schema/mv_staleness")
        assert resp.status_code in (200, 400, 404, 503)

    def test_mv_refresh_loop_endpoint(self, provisa_url, http_client):
        """MV refresh loop endpoint should exist."""
        resp = http_client.post(f"{provisa_url}/schema/mv_refresh", json={"mv_name": "test_mv"})
        assert resp.status_code in (200, 400, 404, 503)

    def test_mv_staleness_state_retrieval(self, provisa_url, http_client):
        """Staleness state should be retrievable."""
        resp = http_client.get(f"{provisa_url}/schema/mv_staleness/test_mv")
        assert resp.status_code in (200, 400, 404, 503)


class TestREQ221HasuraV2Endpoints:
    """REQ-221: Hasura v2 action and event-trigger endpoints."""

    def test_hasura_action_endpoint_exists(self, provisa_url, http_client):
        """Hasura action endpoint should exist."""
        resp = http_client.post(f"{provisa_url}/hasura/action", json={"action": "test_action"})
        assert resp.status_code in (200, 400, 403, 404, 503)

    def test_hasura_event_trigger_endpoint_exists(self, provisa_url, http_client):
        """Hasura event trigger endpoint should exist."""
        resp = http_client.post(
            f"{provisa_url}/hasura/event", json={"event": "test_event", "table": "test_table"}
        )
        assert resp.status_code in (200, 400, 403, 404, 503)

    def test_hasura_metadata_endpoint(self, provisa_url, http_client):
        """Hasura metadata endpoint should be available."""
        resp = http_client.get(f"{provisa_url}/hasura/metadata")
        assert resp.status_code in (200, 400, 404, 503)


class TestREQ363SQLAlchemyDialectIntrospection:
    """REQ-363: SQLAlchemy dialect introspection via /data/graphql."""

    def test_graphql_introspection_endpoint(self, provisa_url, http_client):
        """GraphQL introspection endpoint should exist."""
        resp = http_client.post(
            f"{provisa_url}/data/graphql", json={"query": "{ __schema { types { name } } }"}
        )
        assert resp.status_code in (200, 400, 500)

    def test_dialect_introspection_query(self, provisa_url, http_client):
        """Should support dialect introspection queries."""
        resp = http_client.post(
            f"{provisa_url}/data/graphql",
            json={"query": '{ __type(name: "String") { name fields { name } } }'},
        )
        assert resp.status_code in (200, 400, 500)

    def test_role_based_filtering(self, provisa_url, http_client):
        """GraphQL should respect role-based field filtering."""
        headers = {"X-Hasura-Role": "user"}
        resp = http_client.post(
            f"{provisa_url}/data/graphql", json={"query": "{ tables { name } }"}, headers=headers
        )
        assert resp.status_code in (200, 400, 403, 500)


class TestREQ372TimeTravelQueries:
    """REQ-372: Time-travel queries via as_of argument."""

    def test_as_of_argument_support(self, provisa_url, http_client):
        """Queries should support as_of argument for time-travel."""
        resp = http_client.post(
            f"{provisa_url}/data/graphql",
            json={"query": '{ table_name(as_of: "2026-06-27T00:00:00Z") { id } }'},
        )
        assert resp.status_code in (200, 400, 500)

    def test_iceberg_time_travel(self, provisa_url, http_client):
        """Iceberg sources should support time-travel."""
        resp = http_client.post(
            f"{provisa_url}/data/graphql",
            json={"query": '{ iceberg_table(as_of: "2026-01-01") { snapshot_id } }'},
        )
        assert resp.status_code in (200, 400, 500)

    def test_delta_lake_time_travel(self, provisa_url, http_client):
        """Delta Lake sources should support time-travel."""
        resp = http_client.post(
            f"{provisa_url}/data/graphql",
            json={"query": '{ delta_table(as_of: "2026-01-01") { version } }'},
        )
        assert resp.status_code in (200, 400, 500)


class TestREQ413FKConstraintDiscovery:
    """REQ-413: FK constraint auto-discovery and relationship generation."""

    def test_fk_discovery_endpoint(self, provisa_url, http_client):
        """FK discovery endpoint should exist."""
        resp = http_client.post(f"{provisa_url}/schema/discover_fk", json={"table": "test_table"})
        assert resp.status_code in (200, 400, 404, 503)

    def test_relationship_generation_from_fk(self, provisa_url, http_client):
        """Relationships should be generated from FK constraints."""
        resp = http_client.post(
            f"{provisa_url}/schema/auto_relationships", json={"table": "test_table"}
        )
        assert resp.status_code in (200, 400, 404, 503)

    def test_fk_constraint_metadata(self, provisa_url, http_client):
        """FK constraint metadata should be retrievable."""
        resp = http_client.get(f"{provisa_url}/schema/fk_constraints/test_table")
        assert resp.status_code in (200, 400, 404, 503)


class TestREQ414DemoSchemaValidation:
    """REQ-414: Demo schema FK relationship coverage validation."""

    def test_demo_schema_fk_validation(self, provisa_url, http_client):
        """Demo schema should validate FK relationship coverage."""
        resp = http_client.get(f"{provisa_url}/schema/validate_demo_schema")
        assert resp.status_code in (200, 400, 404, 503)

    def test_demo_schema_relationships(self, provisa_url, http_client):
        """Demo schema relationships should be discoverable."""
        resp = http_client.get(f"{provisa_url}/schema/demo/relationships")
        assert resp.status_code in (200, 400, 404, 503)


class TestREQ543MutationTriggeredStaleness:
    """REQ-543: Mutation-triggered MV staleness marking and refresh_interval."""

    def test_mutation_marks_mv_stale(self, provisa_url, http_client):
        """Mutations should mark MVs stale."""
        resp = http_client.post(
            f"{provisa_url}/data/graphql",
            json={"query": "mutation { insert_table(objects: [{id: 1}]) { affected_rows } }"},
        )
        assert resp.status_code in (200, 400, 500)

    def test_refresh_interval_default(self, provisa_url, http_client):
        """MV refresh_interval should have sensible default."""
        resp = http_client.get(f"{provisa_url}/schema/mv/refresh_interval")
        assert resp.status_code in (200, 400, 404, 503)

    def test_staleness_after_mutation(self, provisa_url, http_client):
        """MV staleness should be marked after mutation."""
        resp = http_client.post(
            f"{provisa_url}/data/graphql",
            json={
                "query": 'mutation { update_table(where: {id: {_eq: 1}}, _set: {name: "new"}) { affected_rows } }'
            },
        )
        assert resp.status_code in (200, 400, 500)


class TestREQ547SQLLiteralRedaction:
    """REQ-547: SQL literal redaction defaults to true on telemetry."""

    def test_telemetry_endpoint_exists(self, provisa_url, http_client):
        """Telemetry endpoint should exist."""
        resp = http_client.get(f"{provisa_url}/telemetry/spans")
        assert resp.status_code in (200, 400, 404, 503)

    def test_sql_literals_redacted_by_default(self, provisa_url, http_client):
        """SQL literals should be redacted in telemetry by default."""
        resp = http_client.get(f"{provisa_url}/telemetry/config")
        assert resp.status_code in (200, 400, 404, 503)

    def test_redaction_toggle(self, provisa_url, http_client):
        """SQL redaction should be toggleable."""
        resp = http_client.post(
            f"{provisa_url}/telemetry/config", json={"redact_sql_literals": False}
        )
        assert resp.status_code in (200, 400, 404, 503)


class TestREQ549TraceparentPropagation:
    """REQ-549: W3C traceparent header propagation through OTel spans."""

    def test_traceparent_header_propagation(self, provisa_url, http_client):
        """W3C traceparent should propagate through requests."""
        headers = {"traceparent": "00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01"}
        resp = http_client.get(
            f"{provisa_url}/data/graphql", headers=headers, params={"query": "{ tables { name } }"}
        )
        assert resp.status_code in (200, 400, 405, 500)

    def test_trace_id_in_response_headers(self, provisa_url, http_client):
        """Response should include trace headers."""
        headers = {"traceparent": "00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01"}
        resp = http_client.get(
            f"{provisa_url}/data/graphql", headers=headers, params={"query": "{ tables { name } }"}
        )
        assert resp.status_code in (200, 400, 405, 500)

    def test_span_propagation_to_downstream(self, provisa_url, http_client):
        """Spans should propagate to downstream services."""
        headers = {"traceparent": "00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01"}
        resp = http_client.post(
            f"{provisa_url}/data/graphql", json={"query": "{ tables { name } }"}, headers=headers
        )
        assert resp.status_code in (200, 400, 500)


class TestMultiREQIntegration:
    """Integration scenarios spanning multiple requirements."""

    def test_graphql_schema_with_mv_and_fk(self, provisa_url, http_client):
        """GraphQL schema should include MVs and FK relationships (REQ-135, REQ-413)."""
        resp = http_client.post(
            f"{provisa_url}/data/graphql", json={"query": "{ __schema { types { name } } }"}
        )
        assert resp.status_code in (200, 400, 500)

    def test_mutation_with_redacted_telemetry(self, provisa_url, http_client):
        """Mutations should have redacted SQL in telemetry (REQ-543, REQ-547)."""
        headers = {"traceparent": "00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01"}
        resp = http_client.post(
            f"{provisa_url}/data/graphql",
            json={"query": "mutation { insert_table(objects: [{id: 1}]) { affected_rows } }"},
            headers=headers,
        )
        assert resp.status_code in (200, 400, 500)

    def test_time_travel_query_with_hasura_filtering(self, provisa_url, http_client):
        """Time-travel queries should respect Hasura role filtering (REQ-372, REQ-363)."""
        headers = {"X-Hasura-Role": "user"}
        resp = http_client.post(
            f"{provisa_url}/data/graphql",
            json={"query": '{ table(as_of: "2026-01-01") { id } }'},
            headers=headers,
        )
        assert resp.status_code in (200, 400, 403, 500)

    def test_mv_refresh_with_path_routing(self, provisa_url, http_client):
        """MV refresh should route path columns correctly (REQ-160, REQ-152)."""
        resp = http_client.post(
            f"{provisa_url}/schema/mv_refresh", json={"mv_name": "cross_source_mv"}
        )
        assert resp.status_code in (200, 400, 404, 503)

    def test_demo_schema_with_hasura_actions(self, provisa_url, http_client):
        """Demo schema should work with Hasura actions (REQ-414, REQ-221)."""
        resp = http_client.post(f"{provisa_url}/hasura/action", json={"action": "demo_action"})
        assert resp.status_code in (200, 400, 403, 404, 503)
