receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: provisa
  otlphttp/parquet:
    endpoint: http://otlp2parquet:4318
    tls:
      insecure: true
  debug:
    verbosity: basic

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/parquet, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, otlphttp/parquet]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/parquet, debug]
