# Copyright (c) 2026 Kenneth Stott
# Canary: 4d5e6f7a-8b9c-0123-def0-123456789004
#
# This source code is licensed under the Business Source License 1.1
# found in the LICENSE file in the root directory of this source tree.
#
# NOTICE: Use of this software for training artificial intelligence or
# machine learning models is strictly prohibited without explicit written
# permission from the copyright holder.

"""Developer-facing data endpoints: compile, submit, proto, sql.

These endpoints are split from endpoint.py (which hit 1000+ lines) to keep
each module under the project's 1000-line limit.
"""

from __future__ import annotations

import asyncio
import logging
from typing import TYPE_CHECKING

from fastapi import APIRouter, Header, HTTPException, Request
from fastapi.responses import Response
from pydantic import BaseModel

if TYPE_CHECKING:
    from provisa.executor.trino import QueryResult

from provisa.api.admin._dev_shared import detect_target
from provisa.compiler.rls import RLSContext
from provisa.compiler.sql_gen import qualify_with_catalogs, rewrite_semantic_to_physical
from provisa.security.rights import Capability, InsufficientRightsError, check_capability
from provisa.transpiler.router import Route, decide_route
from provisa.transpiler.transpile import transpile, transpile_to_trino

log = logging.getLogger(__name__)

router = APIRouter(prefix="/data", tags=["data"])


class SQLRequest(BaseModel):
    sql: str
    role: str = "admin"
    discovery_mode: bool = False


def _resolve_role_id(raw_request: Request, x_provisa_role: str | None, request_role: str) -> str:
    auth_role = getattr(raw_request.state, "role", None)
    return auth_role or x_provisa_role or request_role


@router.get("/proto/{role_id}")
async def proto_endpoint(role_id: str):
    """Return the .proto file content for a role as text/plain."""
    from provisa.api.app import state

    if role_id not in state.proto_files:
        raise HTTPException(
            status_code=404,
            detail=f"No proto file available for role {role_id!r}",
        )
    return Response(content=state.proto_files[role_id], media_type="text/plain")


async def _execute_govdata(source_id: str, sql: str, state) -> "QueryResult":
    log.warning("_execute_govdata called: sql=%s", sql[:300])
    from provisa.core.models import GovDataSource, GovDataSubject
    from provisa.core.secrets import resolve_secrets
    from provisa.executor.trino import QueryResult
    from provisa.govdata.source import execute_query

    pool = state.pg_pool
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            "SELECT username, database FROM sources WHERE id = $1",
            source_id,
        )

    api_key = resolve_secrets(row["username"] or "")
    database = row["database"] or ""

    all_govdata_schemas = [s.strip().lower() for s in database.split(",") if s.strip()]

    # Only instantiate schemas actually referenced in the SQL — instantiating all
    # schemas in the source's database list causes JDBC errors for schemas not cached locally.
    # Strip SQL quotes before regex so both "fec"."candidates" and fec.candidates are matched.
    import re as _re

    _sql_unquoted = sql.replace('"', "").replace("`", "")
    _sql_schemas = {m.group(1).lower() for m in _re.finditer(r"\b(\w+)\.\w+", _sql_unquoted)}
    govdata_schemas = [s for s in all_govdata_schemas if s in _sql_schemas] or all_govdata_schemas

    loop = asyncio.get_event_loop()

    gds = GovDataSource(
        id=source_id,
        subject=GovDataSubject.all,
        govdata_schemas=govdata_schemas,
        domain_id="default",
        api_key=api_key,
    )

    # Calcite/GovData uses lowercase schema names. Quoted identifiers ("ref"."table") are required
    # for reserved-word schemas (e.g. ref, fec). Keep quotes as generated by the compiler.
    # Also convert LIMIT n → FETCH FIRST n ROWS ONLY (Calcite Oracle syntax).
    import re as _re

    govdata_sql = sql
    govdata_sql = _re.sub(
        r"\bLIMIT\s+(\d+)\b", r"FETCH FIRST \1 ROWS ONLY", govdata_sql, flags=_re.IGNORECASE
    )
    govdata_sql = _re.sub(r"\)\s+AS\s+(\w)", r") \1", govdata_sql, flags=_re.IGNORECASE)
    # Calcite Oracle mode rejects subquery aliases entirely in some contexts.
    # Unwrap SELECT * FROM (inner) alias FETCH FIRST n ROWS ONLY → inner FETCH FIRST n ROWS ONLY
    _unwrap = _re.match(
        r"^\s*SELECT\s+\*\s+FROM\s*\(\s*(.*?)\s*\)\s+\w+\s+(FETCH\s+FIRST\s+\d+\s+ROWS\s+ONLY)\s*$",
        govdata_sql,
        flags=_re.IGNORECASE | _re.DOTALL,
    )
    if _unwrap:
        govdata_sql = f"{_unwrap.group(1).strip()} {_unwrap.group(2)}"
    rows_as_dicts = await loop.run_in_executor(None, lambda: execute_query(gds, govdata_sql))

    if not rows_as_dicts:
        return QueryResult(rows=[], column_names=[])

    column_names = list(rows_as_dicts[0].keys())
    rows = [tuple(r[c] for c in column_names) for r in rows_as_dicts]
    return QueryResult(rows=rows, column_names=column_names)


@router.post("/sql")
async def sql_endpoint(
    raw_request: Request,
    request: SQLRequest,
    x_provisa_role: str | None = Header(None),
    accept: str | None = Header(None),
):
    """Execute raw SQL through Stage 2 governance (REQ-264, REQ-266, REQ-267).

    Pipeline:
      1. Parse incoming SQL with SQLGlot.
      2. Construct GovernanceContext from the request role.
      3. Reject (HTTP 403) any table not in the role's schema scope.
      4. Apply Stage 2 governance: RLS, masking, visibility, ceiling.
      5. Route and execute the governed SQL.
    """
    import sqlglot
    import sqlglot.expressions as exp

    from provisa.api.app import state
    from provisa.api.data.endpoint import _parse_accept, _format_response
    from provisa.compiler.stage2 import (
        apply_governance,
        build_governance_context,
        extract_sources,
    )
    from provisa.executor.direct import execute_direct
    from provisa.executor.trino import execute_trino

    role_id = _resolve_role_id(raw_request, x_provisa_role, request.role)

    if role_id not in state.schemas:
        raise HTTPException(status_code=400, detail=f"No schema for role {role_id!r}")

    role = state.roles.get(role_id)
    if role and not request.discovery_mode:
        try:
            check_capability(role, Capability.QUERY_DEVELOPMENT)
        except InsufficientRightsError as e:
            raise HTTPException(status_code=403, detail=str(e))
        try:
            check_capability(role, Capability.AD_HOC_QUERY)
        except InsufficientRightsError as e:
            raise HTTPException(status_code=403, detail=str(e))

    ctx = state.contexts[role_id]
    rls = state.rls_contexts.get(role_id, RLSContext.empty())

    # --- Step 1: Parse semantic SQL via SQLGlot (REQ-266) ---
    # Strip provisa-params comment before SQLGlot (it strips comments); carry params forward.
    from provisa.compiler.params import extract_params_comment

    raw_sql, embedded_params = extract_params_comment(request.sql)
    from provisa.compiler.params import extract_relationship_guard_comment

    raw_sql, _sql_opts_out = extract_relationship_guard_comment(raw_sql)

    # Clients write semantic SQL (domain.field_name refs). Physical translation
    # happens after routing — governance runs on semantic refs.
    try:
        parsed_tree = sqlglot.parse_one(raw_sql, read="postgres")
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"SQL parse error: {exc}")

    # --- Step 1b: Normalize table refs — qualify unique unquoted names ---
    normalized_sql = rewrite_semantic_to_physical(raw_sql, ctx)
    try:
        parsed_tree = sqlglot.parse_one(normalized_sql, read="postgres")
    except Exception:
        normalized_sql = raw_sql  # fall back to comment-stripped sql if normalize broke it

    # --- Step 2: Build GovernanceContext — table_map includes semantic refs ---
    gov_ctx = build_governance_context(
        role_id,
        rls,
        state.masking_rules,
        ctx,
        getattr(state, "tables", []),
    )

    # --- Step 3: Validate SQL against role-scoped GraphQL-equivalent rules ---
    from provisa.compiler.sql_validator import validate_sql

    raw_tables = getattr(state, "tables", [])

    # In discovery mode, augment table_map with all tables from all contexts
    if request.discovery_mode:
        for all_ctx in state.contexts.values():
            for meta in all_ctx.tables.values():
                gov_ctx.table_map.setdefault(meta.table_name, meta.table_id)
                gov_ctx.table_map.setdefault(f"{meta.schema_name}.{meta.table_name}", meta.table_id)

    _role_guard = (role or {}).get("relationship_guard", True)
    _bypass_guard = (not _role_guard) and _sql_opts_out
    violations = validate_sql(
        normalized_sql,
        ctx,
        gov_ctx,
        role or {},
        raw_tables,
        discovery_mode=request.discovery_mode,
        bypass_relationship_guard=_bypass_guard,
        bypass_uncovered_relationships=True,
    )

    _role_domain_access = (role or {}).get("domain_access") or []
    if not request.discovery_mode and "*" not in _role_domain_access:
        # Reject any table not in the role's schema scope (fast path for unknown tables)
        for tbl in parsed_tree.find_all(exp.Table):
            tbl_name = tbl.name
            tbl_db = tbl.db
            full_key = f"{tbl_db}.{tbl_name}" if tbl_db else tbl_name
            if full_key not in gov_ctx.table_map and tbl_name not in gov_ctx.table_map:
                from provisa.compiler.sql_validator import ValidationViolation

                ref = full_key or tbl_name
                violations.append(
                    ValidationViolation(
                        "V000",
                        f"Table {ref!r} is not accessible for role {role_id!r}",
                    )
                )

    if violations:
        msgs = [f"[{v.code}] {v.message}" for v in violations]
        log.warning("[SQL] role=%s violations: %s", role_id, msgs)
        raise HTTPException(
            status_code=403,
            detail={"violations": [{"code": v.code, "message": v.message} for v in violations]},
        )

    # --- Step 4: Governance on normalized SQL ---
    governed_semantic = apply_governance(normalized_sql, gov_ctx)

    # --- Step 5: Routing decision (on governed semantic SQL) ---
    sources = extract_sources(governed_semantic, gov_ctx, ctx)

    _default_source = next(
        (sid for sid, t in state.source_types.items() if t in ("postgresql", "mysql", "sqlite")),
        next(iter(state.source_pools.source_ids), "pg"),
    )

    decision = decide_route(
        sources=sources or {_default_source},
        source_types=state.source_types,
        source_dialects=state.source_dialects,
        has_json_extract="->>" in governed_semantic,
        source_dsns=getattr(state, "source_dsns", None),
    )

    # --- Step 6: governed_semantic is already physical after Step 1b normalization ---
    governed_physical = governed_semantic

    output_format = _parse_accept(accept)

    # --- Step 7: Execute ---
    try:
        exec_params = embedded_params or None
        _govdata_sid = next(
            (
                sid
                for sid in (sources or {_default_source})
                if state.source_types.get(sid) == "govdata"
            ),
            None,
        )
        if _govdata_sid:
            result = await _execute_govdata(_govdata_sid, governed_physical, state)
        elif decision.route == Route.TRINO:
            from provisa.api.data.endpoint import _materialize_api_to_trino_cache
            from provisa.cache.hot_tables import build_values_cte_sql
            from provisa.api_source.trino_cache import rewrite_all_from_cache

            _qualified = qualify_with_catalogs(governed_physical, ctx)
            _rewrites, _values_ctes = await _materialize_api_to_trino_cache(_qualified, None, state)
            for _tn, _entry in _values_ctes.items():
                _qualified = build_values_cte_sql(_qualified, _tn, _entry)
            if _rewrites:
                _qualified = rewrite_all_from_cache(_qualified, _rewrites)
            sql_to_run = transpile_to_trino(_qualified)
            _loop = asyncio.get_event_loop()
            if state.trino_conn is None:
                raise HTTPException(status_code=503, detail="Trino connection not available")
            _trino_conn = state.trino_conn
            result = await _loop.run_in_executor(
                None, lambda: execute_trino(_trino_conn, sql_to_run, params=exec_params)
            )
        else:
            dialect = decision.dialect or "postgres"
            sql_to_run = transpile(governed_physical, dialect)
            result = await execute_direct(
                state.source_pools,
                decision.source_id or _default_source,
                sql_to_run,
                exec_params,
            )
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc))

    rows_as_dicts = [dict(zip(result.column_names, row)) for row in result.rows]
    if output_format == "json":
        return {"data": {"sql": rows_as_dicts}}
    from provisa.compiler.sql_gen import ColumnRef

    columns = [
        ColumnRef(alias=None, column=c, field_name=c, nested_in=None) for c in result.column_names
    ]
    return _format_response(result.rows, columns, "sql", output_format)


class NLToSQLRequest(BaseModel):
    question: str
    role: str = "admin"


@router.post("/nl-to-sql")
async def nl_to_sql_endpoint(
    raw_request: Request,
    request: NLToSQLRequest,
    x_provisa_role: str | None = Header(None),
):
    """Translate a natural-language question to Semantic SQL via Claude.

    Validates the generated SQL with sqlglot and retries (up to 3 attempts)
    feeding parse errors back to Claude.
    """
    import sqlglot

    from provisa.api.app import state
    from provisa.compiler.sql_gen import rewrite_semantic_to_physical
    from provisa.llm.client import ProviasLLMClient

    role_id = _resolve_role_id(raw_request, x_provisa_role, request.role)
    if role_id not in state.contexts:
        raise HTTPException(status_code=400, detail=f"No schema for role {role_id!r}")

    ctx = state.contexts[role_id]

    from provisa.compiler.naming import domain_to_sql_name

    from provisa.compiler.sql_validator import validate_sql
    from provisa.compiler.stage2 import build_governance_context

    rls = state.rls_contexts.get(role_id, RLSContext.empty())
    gov_ctx = build_governance_context(
        role_id, rls, state.masking_rules, ctx, getattr(state, "tables", [])
    )
    role_obj = state.roles.get(role_id)
    raw_tables = getattr(state, "tables", [])

    from provisa.compiler.sql_gen import TableMeta as _TableMeta
    from provisa.cypher.label_map import CypherLabelMap as _CLM

    # Collect all user-visible tables (root + join targets, excluding ops/meta).
    seen_type_names: set[str] = set()
    all_tables: list[_TableMeta] = []
    for tbl in ctx.tables.values():
        if tbl.type_name not in seen_type_names:
            seen_type_names.add(tbl.type_name)
            all_tables.append(tbl)
    for jm in ctx.joins.values():
        if jm.target.type_name not in seen_type_names:
            seen_type_names.add(jm.target.type_name)
            all_tables.append(jm.target)

    def _sql_domain(domain_id: str | None) -> str:
        return domain_to_sql_name(domain_id) if domain_id else "default"

    _lm = _CLM.from_schema(ctx)
    _user_domains = {
        d for d in (n.domain_id for n in _lm.nodes.values()) if d not in (None, "ops", "meta")
    }
    # type_name → NodeMapping for user-visible, non-traversal-only nodes
    _user_nodes = {
        tn: nm
        for tn, nm in _lm.nodes.items()
        if nm.domain_id in _user_domains and not nm.traversal_only
    }
    # table_name → type_name index for pass-1 response parsing
    _table_name_to_type: dict[str, str] = {nm.table_name: tn for tn, nm in _user_nodes.items()}

    # Pass 1: ask table_selection LLM which tables the question needs.
    table_list = ", ".join(
        f"{_sql_domain(nm.domain_id)}.{nm.table_name}" for nm in _user_nodes.values()
    )
    _table_selector = ProviasLLMClient("table_selection")
    pass1_text = await _table_selector.complete(
        prompt=f"Tables: {table_list}\n\nQuestion: {request.question}",
        system=(
            "You are a table selector. Given a natural-language question and a list of available tables, "
            "reply with ONLY a comma-separated list of the table names (without domain prefix) that are "
            "needed to answer the question. No explanation. No punctuation other than commas."
        ),
        max_tokens=256,
    )
    selected_raw = [t.strip().split(".")[-1] for t in pass1_text.split(",") if t.strip()]
    selected_types: set[str] = {
        _table_name_to_type[name] for name in selected_raw if name in _table_name_to_type
    }
    # Fall back to all user tables if pass 1 returned nothing recognisable.
    if not selected_types:
        selected_types = set(_user_nodes)

    # Find shortest join paths between every selected-table pair.
    multihop_lines: list[str] = []
    _seen_path_keys: set[tuple[str, ...]] = set()
    for src_tn in selected_types:
        src_nm = _lm.nodes[src_tn]
        for tgt_tn in selected_types:
            if src_tn == tgt_tn:
                continue
            paths = _lm.find_paths(src_tn, tgt_tn, max_hops=4)
            multihop_paths = [p for p in paths if len(p) >= 2]
            if not multihop_paths:
                continue
            shortest = min(multihop_paths, key=len)
            path_key = tuple(
                f"{r.source_label}:{r.join_source_column}:{r.target_label}" for r in shortest
            )
            if path_key in _seen_path_keys:
                continue
            _seen_path_keys.add(path_key)
            node_chain = [src_nm] + [_lm.nodes[r.target_label] for r in shortest]
            hops_str = " → ".join(f"{_sql_domain(n.domain_id)}.{n.table_name}" for n in node_chain)
            multihop_lines.append(f"Multi-hop path ({len(shortest)} hops): {hops_str}")
            for r in shortest:
                s_nm = _lm.nodes[r.source_label]
                t_nm = _lm.nodes[r.target_label]
                multihop_lines.append(
                    f"  JOIN {_sql_domain(t_nm.domain_id)}.{t_nm.table_name}"
                    f" ON {s_nm.table_name}.{r.join_source_column}"
                    f" = {t_nm.table_name}.{r.join_target_column}"
                )

    # Build schema block restricted to selected tables + intermediate hop tables.
    hop_type_names: set[str] = set()
    for src_tn in selected_types:
        for tgt_tn in selected_types:
            if src_tn == tgt_tn:
                continue
            for path in _lm.find_paths(src_tn, tgt_tn, max_hops=4):
                for r in path:
                    hop_type_names.add(r.source_label)
                    hop_type_names.add(r.target_label)
    relevant_type_names = selected_types | hop_type_names

    schema_lines: list[str] = []
    for tbl in all_tables:
        if tbl.type_name not in relevant_type_names:
            continue
        cols = ctx.aggregate_columns.get(tbl.table_id, [])
        col_list = ", ".join(col_name for col_name, _ in cols)
        schema_lines.append(f"Table {_sql_domain(tbl.domain_id)}.{tbl.table_name}")
        schema_lines.append(f"  Columns: {col_list or '(unknown)'}")
        for (src_type, _), jm in ctx.joins.items():
            if src_type == tbl.type_name:
                schema_lines.append(
                    f"  Approved JOIN: {_sql_domain(jm.target.domain_id)}.{jm.target.table_name} "
                    f"ON {tbl.table_name}.{jm.source_column} = {jm.target.table_name}.{jm.target_column}"
                )

    schema_block = "\n".join(schema_lines)
    if multihop_lines:
        schema_block += (
            "\n\nMulti-hop join paths (use these when tables are not directly joined):\n"
            + "\n".join(multihop_lines)
        )

    sql_gen_system = (
        "You are a SQL generator for the Provisa data platform.\n"
        "Output ONLY a valid PostgreSQL SELECT statement — no explanation, no markdown, no code fences.\n\n"
        f"Available tables and approved joins:\n{schema_block}\n\n"
        "STRICT RULES — violating any rule causes a validation error:\n"
        "1. Table names: use domain.table_name exactly as listed (e.g. pet_store.pets). Never quote schema names.\n"
        "2. Column names: use ONLY the column names listed under each table, exactly as shown (case-sensitive). Never invent names.\n"
        "3. JOINs: use ONLY the 'Approved JOIN' conditions listed above, character for character. "
        "Never write a JOIN ON condition that is not in the list above.\n"
        "4. Include a LIMIT clause (default 100).\n"
        "5. Output only the SQL statement."
    )

    _sql_gen = ProviasLLMClient("sql_generation")
    last_error: str = ""
    last_sql: str = ""
    attempt: int = 0
    current_prompt: str = request.question

    for attempt in range(1, 4):
        if last_error:
            current_prompt = (
                f"{request.question}\n\nPrevious attempt:\n{last_sql}\n\n"
                f"Error: {last_error}\nFix it and output only the corrected SQL."
            )

        last_sql = await _sql_gen.complete(
            prompt=current_prompt,
            system=sql_gen_system,
            max_tokens=1024,
        )
        if last_sql.startswith("```"):
            last_sql = "\n".join(
                line for line in last_sql.splitlines() if not line.strip().startswith("```")
            ).strip()

        # Validate syntax
        try:
            sqlglot.parse_one(last_sql, read="postgres")
        except Exception as exc:
            last_error = str(exc)
            continue

        # Validate governance (column names, join conditions, table access)
        normalized = rewrite_semantic_to_physical(last_sql, ctx)
        violations = validate_sql(normalized, ctx, gov_ctx, role_obj or {}, raw_tables)
        if violations:
            last_error = "; ".join(f"[{v.code}] {v.message}" for v in violations)
            continue

        last_error = ""
        break

    if last_error:
        raise HTTPException(
            status_code=422, detail=f"Could not generate valid SQL after 3 attempts: {last_error}"
        )

    return {"sql": last_sql, "attempts": attempt}


class QueryRequest(BaseModel):
    query: str
    params: dict = {}
    variables: dict | None = None
    role: str = "admin"


@router.post("/query")
async def unified_query_endpoint(
    raw_request: Request,
    request: QueryRequest,
    x_provisa_role: str | None = Header(None),
):
    """Execute a GraphQL, SQL, or Cypher query; auto-detected from syntax.

    Returns { columns, rows } for Cypher/SQL.
    Returns { data } for GraphQL (native format).
    """

    role_id = _resolve_role_id(raw_request, x_provisa_role, request.role)

    target = detect_target(request.query)

    if target == "cypher":
        from provisa.api.rest.cypher_router import CypherRequest, cypher_query

        body = CypherRequest(query=request.query, params=request.params)
        return await cypher_query(body, raw_request)

    if target == "graphql":
        from provisa.api.data.endpoint import graphql_endpoint
        from provisa.api.data.endpoint import GraphQLRequest as GQLRequest

        gql_req = GQLRequest(query=request.query, variables=request.variables, role=role_id)
        return await graphql_endpoint(raw_request, gql_req)

    # SQL
    sql_req = SQLRequest(sql=request.query, role=role_id)
    return await sql_endpoint(raw_request, sql_req, x_provisa_role=x_provisa_role)
