#!/usr/bin/env bash
# First-launch setup for Linux AppImage.
# Loads bundled Docker images and installs the provisa CLI.
set -euo pipefail

APPDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGES_DIR="${APPDIR}/images"
COMPOSE_DIR="${APPDIR}/compose"
PROVISA_HOME="${HOME}/.provisa"
SENTINEL="${PROVISA_HOME}/.first-launch-complete"
LOCAL_BIN="${HOME}/.local/bin"

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
info() { printf "${CYAN}[provisa]${NC} %s\n" "$*"; }
ok()   { printf "${GREEN}[provisa]${NC} %s\n" "$*"; }
err()  { printf "${RED}[provisa]${NC} %s\n" "$*" >&2; }

# ── Derive Trino worker count from RAM budget ─────────────────────────────────
_workers_from_budget() {
  local gb="$1"
  if   [ "$gb" -ge 96 ]; then echo 4
  elif [ "$gb" -ge 48 ]; then echo 2
  elif [ "$gb" -ge 24 ]; then echo 1
  else echo 0
  fi
}

# ── Ask RAM budget at first launch ────────────────────────────────────────────
# Sets global: TRINO_WORKERS
ask_ram_budget() {
  local total_gb
  total_gb="$(awk '/MemTotal/ {printf "%d", $2/1024/1024}' /proc/meminfo)"

  printf "\n${BOLD}RAM Budget${NC}\n"
  printf "How much RAM should Provisa use? (host total: %dGB)\n\n" "$total_gb"

  local options=()
  for size in 4 8 16 32 64 128; do
    [ "$size" -le "$total_gb" ] && options+=("${size}GB")
  done
  options+=("All (${total_gb}GB)")

  local i=1
  for opt in "${options[@]}"; do
    printf "  [%d] %s\n" "$i" "$opt"
    i=$((i + 1))
  done
  printf "\n"

  local choice
  while true; do
    printf "Enter choice [1-%d]: " "${#options[@]}"
    read -r choice
    if [[ "$choice" =~ ^[0-9]+$ ]] && [ "$choice" -ge 1 ] && [ "$choice" -le "${#options[@]}" ]; then
      break
    fi
    printf "Invalid choice. Try again.\n"
  done

  local selected="${options[$((choice - 1))]}"
  local budget_gb
  if [[ "$selected" == All* ]]; then
    budget_gb="$total_gb"
  else
    budget_gb="${selected%GB}"
  fi

  TRINO_WORKERS="$(_workers_from_budget "$budget_gb")"
  ok "RAM budget: ${budget_gb}GB → Trino workers: ${TRINO_WORKERS}"
}

# ── Check Docker ───────────────────────────────────────────────────────────────
check_docker() {
  if ! docker info &>/dev/null; then
    err "Docker is not running. Start Docker Engine and re-run."
    exit 1
  fi
  ok "Docker is running."
}

# ── Load images ────────────────────────────────────────────────────────────────
load_images() {
  info "Loading bundled container images (no network required)..."
  local count=0
  for tar_file in "${IMAGES_DIR}"/*.tar; do
    [ -f "$tar_file" ] || continue
    info "  Loading: $(basename "$tar_file")"
    docker load -i "$tar_file"
    count=$((count + 1))
  done
  ok "Loaded ${count} images."
}

# ── Write config ───────────────────────────────────────────────────────────────
write_config() {
  mkdir -p "$PROVISA_HOME"
  if [ -f "${PROVISA_HOME}/config.yaml" ]; then
    return
  fi
  cat > "${PROVISA_HOME}/config.yaml" <<YAML
# Provisa configuration — generated by AppImage installer
project_dir: "${COMPOSE_DIR}"
ui_port: 3000
api_port: 8000
auto_open_browser: true
runtime: docker
federation_workers: ${TRINO_WORKERS}
YAML
  ok "Config written to ${PROVISA_HOME}/config.yaml"
}

# ── Install CLI ────────────────────────────────────────────────────────────────
install_cli() {
  mkdir -p "$LOCAL_BIN"
  cp "${APPDIR}/provisa-cli" "${LOCAL_BIN}/provisa"
  chmod +x "${LOCAL_BIN}/provisa"
  ok "CLI installed to ${LOCAL_BIN}/provisa"

  case ":${PATH}:" in
    *":${LOCAL_BIN}:"*) ;;
    *)
      printf "\n${CYAN}[provisa]${NC} Add %s to your PATH:\n" "$LOCAL_BIN"
      printf "  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc\n"
      printf "  source ~/.bashrc\n\n"
      ;;
  esac
}

# ── Main ───────────────────────────────────────────────────────────────────────
main() {
  TRINO_WORKERS=0

  printf "\n${BOLD}Provisa — First Launch Setup${NC}\n"
  printf "═══════════════════════════════════════════\n\n"
  info "Setting up Provisa (no internet required)..."

  check_docker
  ask_ram_budget
  load_images
  write_config
  install_cli

  mkdir -p "$PROVISA_HOME"
  touch "$SENTINEL"
  ok "First-launch setup complete."
  printf "\n${GREEN}${BOLD}Provisa is ready.${NC}\n"
  printf "Run: ${BOLD}provisa start${NC}\n\n"
}

main "$@"
