#!/usr/bin/env bash
# First-launch setup for Linux AppImage.
# Loads bundled Docker images and installs the provisa CLI.
# Always uses bundled rootless dockerd — no system Docker required.
set -euo pipefail

APPDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGES_DIR="${APPDIR}/images"
COMPOSE_DIR="${APPDIR}/compose"
PROVISA_HOME="${HOME}/.provisa"
SENTINEL="${PROVISA_HOME}/.first-launch-complete"
LOCAL_BIN="${HOME}/.local/bin"

BUNDLED_ROOTLESS="${APPDIR}/bin/dockerd-rootless.sh"
BUNDLED_SOCKET="${PROVISA_HOME}/run/docker.sock"
BUNDLED_DATA="${PROVISA_HOME}/docker-data"
BUNDLED_PID="${PROVISA_HOME}/run/dockerd.pid"

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
info() { printf "${CYAN}[provisa]${NC} %s\n" "$*"; }
ok()   { printf "${GREEN}[provisa]${NC} %s\n" "$*"; }
err()  { printf "${RED}[provisa]${NC} %s\n" "$*" >&2; }

# ── Derive Trino worker count from RAM budget ─────────────────────────────────
_workers_from_budget() {
  local gb="$1"
  if   [ "$gb" -ge 96 ]; then echo 4
  elif [ "$gb" -ge 48 ]; then echo 2
  elif [ "$gb" -ge 24 ]; then echo 1
  else echo 0
  fi
}

# ── Ask RAM budget at first launch ────────────────────────────────────────────
# Sets global: TRINO_WORKERS
ask_ram_budget() {
  local total_gb
  total_gb="$(awk '/MemTotal/ {printf "%d", $2/1024/1024}' /proc/meminfo)"

  printf "\n${BOLD}RAM Budget${NC}\n"
  printf "How much RAM should Provisa use? (host total: %dGB)\n\n" "$total_gb"

  local options=()
  for size in 4 8 16 32 64 128; do
    [ "$size" -le "$total_gb" ] && options+=("${size}GB")
  done
  options+=("All (${total_gb}GB)")

  local i=1
  for opt in "${options[@]}"; do
    printf "  [%d] %s\n" "$i" "$opt"
    i=$((i + 1))
  done
  printf "\n"

  local choice
  while true; do
    printf "Enter choice [1-%d]: " "${#options[@]}"
    read -r choice
    if [[ "$choice" =~ ^[0-9]+$ ]] && [ "$choice" -ge 1 ] && [ "$choice" -le "${#options[@]}" ]; then
      break
    fi
    printf "Invalid choice. Try again.\n"
  done

  local selected="${options[$((choice - 1))]}"
  local budget_gb
  if [[ "$selected" == All* ]]; then
    budget_gb="$total_gb"
  else
    budget_gb="${selected%GB}"
  fi

  TRINO_WORKERS="$(_workers_from_budget "$budget_gb")"
  ok "RAM budget: ${budget_gb}GB → Trino workers: ${TRINO_WORKERS}"
}

# ── Start bundled rootless Docker ─────────────────────────────────────────────
start_docker() {
  if [ ! -x "$BUNDLED_ROOTLESS" ]; then
    err "Bundled Docker runtime not found at ${APPDIR}/bin/ — reinstall Provisa."
    exit 1
  fi

  mkdir -p "${PROVISA_HOME}/run" "$BUNDLED_DATA"
  export XDG_RUNTIME_DIR="${PROVISA_HOME}/run"
  export DOCKER_HOST="unix://${BUNDLED_SOCKET}"
  export PATH="${APPDIR}/bin:${PATH}"

  info "Starting bundled Docker runtime..."
  "$BUNDLED_ROOTLESS" \
    --data-root "$BUNDLED_DATA" \
    --host "unix://${BUNDLED_SOCKET}" \
    --pidfile "$BUNDLED_PID" \
    --log-level error \
    >/dev/null 2>&1 &

  local retries=30
  while [ $retries -gt 0 ]; do
    docker info &>/dev/null 2>&1 && break
    sleep 1
    retries=$((retries - 1))
  done
  if [ $retries -eq 0 ]; then
    err "Bundled Docker failed to start within 30 seconds."
    exit 1
  fi
  ok "Docker started."
}

# ── Load images ────────────────────────────────────────────────────────────────
load_images() {
  info "Loading bundled container images (no network required)..."
  local count=0
  for tar_file in "${IMAGES_DIR}"/*.tar.gz; do
    [ -f "$tar_file" ] || continue
    info "  Loading: $(basename "$tar_file")"
    gunzip -c "$tar_file" | docker load
    count=$((count + 1))
  done
  ok "Loaded ${count} images."
}

# ── Ask hostname ──────────────────────────────────────────────────────────────
ask_hostname() {
  local default="localhost"
  printf "Hostname for Provisa [${default}]: "
  local input
  read -r input
  input="${input//[[:space:]]/}"
  echo "${input:-$default}"
}

# ── Ask UI port ───────────────────────────────────────────────────────────────
ask_ui_port() {
  local default=3000
  local port=""
  while true; do
    printf "Web UI port [${default}]: "
    read -r port
    port="${port//[[:space:]]/}"
    port="${port:-$default}"
    if [[ "$port" =~ ^[0-9]+$ ]] && [ "$port" -ge 1024 ] && [ "$port" -le 65535 ]; then
      break
    fi
    printf "Invalid port. Enter a number between 1024 and 65535.\n"
  done
  echo "$port"
}

# ── Write config ───────────────────────────────────────────────────────────────
write_config() {
  mkdir -p "$PROVISA_HOME"
  if [ -f "${PROVISA_HOME}/config.yaml" ]; then
    return
  fi

  local hostname
  hostname="$(ask_hostname)"
  local ui_port
  ui_port="$(ask_ui_port)"
  local api_port=$(( ui_port + 1 ))

  info "Hostname: ${hostname}  |  UI port: ${ui_port}  |  API port: ${api_port}"

  cat > "${PROVISA_HOME}/config.yaml" <<YAML
# Provisa configuration — generated by AppImage installer
project_dir: "${COMPOSE_DIR}"
hostname: ${hostname}
ui_port: ${ui_port}
api_port: ${api_port}
auto_open_browser: true
runtime: bundled
docker_host: "unix://${BUNDLED_SOCKET}"
federation_workers: ${TRINO_WORKERS}
YAML
  ok "Config written to ${PROVISA_HOME}/config.yaml"
}

# ── Install CLI ────────────────────────────────────────────────────────────────
install_cli() {
  mkdir -p "$LOCAL_BIN"
  cp "${APPDIR}/provisa-cli" "${LOCAL_BIN}/provisa"
  chmod +x "${LOCAL_BIN}/provisa"
  ok "CLI installed to ${LOCAL_BIN}/provisa"

  # Persist DOCKER_HOST so future shells pick it up
  for rc in "${HOME}/.bashrc" "${HOME}/.zshrc"; do
    [ -f "$rc" ] || continue
    if ! grep -q "PROVISA_DOCKER_HOST" "$rc" 2>/dev/null; then
      printf '\n# Provisa bundled Docker runtime\nexport DOCKER_HOST="%s"\n' \
        "unix://${BUNDLED_SOCKET}" >> "$rc"
    fi
  done

  case ":${PATH}:" in
    *":${LOCAL_BIN}:"*) ;;
    *)
      printf "\n${CYAN}[provisa]${NC} Add %s to your PATH:\n" "$LOCAL_BIN"
      printf "  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc\n"
      printf "  source ~/.bashrc\n\n"
      ;;
  esac
}

# ── Main ───────────────────────────────────────────────────────────────────────
main() {
  TRINO_WORKERS=0

  printf "\n${BOLD}Provisa — First Launch Setup${NC}\n"
  printf "═══════════════════════════════════════════\n\n"
  info "Setting up Provisa (no internet required)..."

  start_docker
  ask_ram_budget
  load_images
  write_config
  install_cli

  mkdir -p "$PROVISA_HOME"
  touch "$SENTINEL"
  ok "First-launch setup complete."
  printf "\n${GREEN}${BOLD}Provisa is ready.${NC}\n"
  printf "Run: ${BOLD}provisa start${NC}\n\n"
}

main "$@"
