#!/usr/bin/env bash
# Phase AF2a — First-launch setup: start Lima VM, import images.
# Called by provisa-launcher on first run only.
set -euo pipefail

BUNDLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RESOURCES="${BUNDLE_DIR}/Resources"
IMAGES_DIR="${RESOURCES}/images"
PROVISA_HOME="${HOME}/.provisa"
SENTINEL="${PROVISA_HOME}/.first-launch-complete"
LIMA_VM_NAME="provisa"
LIMA_YAML="${RESOURCES}/provisa-lima.yaml"

ARCH="$(uname -m)"
case "$ARCH" in
  arm64)  BIN_ARCH="arm64" ;;
  x86_64) BIN_ARCH="x86_64" ;;
  *)
    printf "[provisa] Unsupported architecture: %s\n" "$ARCH" >&2
    exit 1
    ;;
esac

LIMACTL="${BUNDLE_DIR}/MacOS/bin/${BIN_ARCH}/limactl"
CTR="${BUNDLE_DIR}/MacOS/bin/${BIN_ARCH}/ctr"

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
info() { printf "${CYAN}[provisa]${NC} %s\n" "$*"; }
ok()   { printf "${GREEN}[provisa]${NC} %s\n" "$*"; }
err()  { printf "${RED}[provisa]${NC} %s\n" "$*" >&2; }

# ── Write Lima VM config if not present ──────────────────────────────────────
write_lima_config() {
  if [ -f "$LIMA_YAML" ]; then
    return
  fi
  cat > "$LIMA_YAML" <<'YAML'
# Provisa Lima VM — airgapped, no network pull required
vmType: vz
os: Linux
arch: host
cpus: 4
memory: "8GiB"
disk: "60GiB"
rosetta:
  enabled: true
  binfmt: true
containerd:
  system: true
  user: false
mounts:
  - location: "~/.provisa"
    writable: true
networks: []
provision:
  - mode: system
    script: |
      #!/bin/bash
      # containerd already managed by Lima containerd integration
      systemctl enable --now containerd || true
YAML
}

# ── Start Lima VM ─────────────────────────────────────────────────────────────
start_lima() {
  info "Starting Provisa VM (first launch — this takes ~2 minutes)..."

  if "$LIMACTL" list --format '{{.Name}}' 2>/dev/null | grep -q "^${LIMA_VM_NAME}$"; then
    local state
    state="$("$LIMACTL" list --format '{{.Status}}' "$LIMA_VM_NAME" 2>/dev/null || echo "unknown")"
    if [ "$state" = "Running" ]; then
      ok "VM already running."
      return 0
    fi
    info "Resuming existing VM..."
    "$LIMACTL" start "$LIMA_VM_NAME"
  else
    write_lima_config
    info "Creating VM from config..."
    "$LIMACTL" start --name="$LIMA_VM_NAME" "$LIMA_YAML"
  fi
  ok "VM started."
}

# ── Import bundled images ─────────────────────────────────────────────────────
import_images() {
  info "Importing bundled container images (no network required)..."
  local count=0
  for tar_file in "${IMAGES_DIR}"/*.tar; do
    [ -f "$tar_file" ] || continue
    local name
    name="$(basename "$tar_file")"
    info "  Importing: ${name}"
    "$LIMACTL" shell "$LIMA_VM_NAME" -- \
      sudo ctr --namespace=default images import "/mnt/lima.hostagent/Users/${USER}/.provisa/images/${name}" \
      2>/dev/null || \
    "$LIMACTL" shell "$LIMA_VM_NAME" -- \
      sudo ctr --namespace=default images import - < "$tar_file"
    count=$((count + 1))
  done
  ok "Imported ${count} images."
}

# ── Copy images into provisa home for VM access ───────────────────────────────
stage_images() {
  local staged="${PROVISA_HOME}/images"
  if [ -d "$staged" ] && [ "$(ls -A "$staged" 2>/dev/null)" ]; then
    return 0
  fi
  mkdir -p "$staged"
  info "Staging images to ${staged}..."
  cp "${IMAGES_DIR}"/*.tar "$staged/"
}

# ── Write config ──────────────────────────────────────────────────────────────
write_config() {
  if [ -f "${PROVISA_HOME}/config.yaml" ]; then
    return
  fi
  mkdir -p "$PROVISA_HOME"
  cat > "${PROVISA_HOME}/config.yaml" <<YAML
# Provisa configuration — generated by DMG installer
project_dir: "${RESOURCES}"
ui_port: 3000
api_port: 8000
auto_open_browser: true
runtime: lima
lima_vm: ${LIMA_VM_NAME}
YAML
  ok "Config written to ${PROVISA_HOME}/config.yaml"
}

# ── Install CLI symlink ───────────────────────────────────────────────────────
install_cli() {
  local cli_src="${RESOURCES}/provisa-cli"
  local cli_dst="/usr/local/bin/provisa"
  if [ -f "$cli_dst" ]; then
    return 0
  fi
  info "Installing provisa CLI to /usr/local/bin/..."
  if [ -w /usr/local/bin ]; then
    cp "$cli_src" "$cli_dst"
    chmod +x "$cli_dst"
  else
    osascript -e "do shell script \"cp '${cli_src}' '${cli_dst}' && chmod +x '${cli_dst}'\" with administrator privileges"
  fi
  ok "CLI installed."
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
  if [ -f "$SENTINEL" ]; then
    exit 0
  fi

  printf "\n${BOLD}Provisa — First Launch Setup${NC}\n"
  printf "═══════════════════════════════════════════\n\n"
  info "Setting up Provisa (no internet required)..."

  mkdir -p "$PROVISA_HOME"
  write_config
  stage_images
  start_lima
  import_images
  install_cli

  touch "$SENTINEL"
  ok "First-launch setup complete."
  printf "\n${GREEN}${BOLD}Provisa is ready.${NC}\n"
  printf "Run: ${BOLD}provisa start${NC}\n\n"
}

main "$@"
