#!/usr/bin/env python3
# Copyright (c) 2026 Kenneth Stott
# Canary: b4f7a923-1e6d-4d2c-e841-8c0f5b3d2a17
#
# This source code is licensed under the Business Source License 1.1
"""Generate stub step definitions in tests/steps/ from .feature files.

Reads all tests/features/REQ-NNN.feature files, extracts unimplemented
Given/When/Then/And steps, and writes stub functions that call pytest.skip.

Usage:
  python scripts/gen_step_stubs.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

FEATURES_DIR = Path("tests/features")
STEPS_DIR = Path("tests/steps")
STUB_FILE = STEPS_DIR / "generated_stubs.py"

_STEP_RE = re.compile(r"^\s+(Given|When|Then|And|But)\s+(.+)$")
_SLUG_RE = re.compile(r"[^a-z0-9]+")


def step_to_func(verb: str, text: str) -> str:
    slug = _SLUG_RE.sub("_", text.lower()).strip("_")[:60]
    return f"step_{verb.lower()}_{slug}"


def generate_stubs(feature_files: list[Path]) -> str:
    seen: set[str] = set()
    steps: list[tuple[str, str, str]] = []

    for fpath in sorted(feature_files):
        req_id = fpath.stem
        for line in fpath.read_text().splitlines():
            m = _STEP_RE.match(line)
            if not m:
                continue
            verb, text = m.group(1), m.group(2).strip()
            func = step_to_func(verb, text)
            if func in seen:
                continue
            seen.add(func)
            steps.append((req_id, verb, text))

    lines = [
        "# Generated by scripts/gen_step_stubs.py. Do not hand-edit.",
        "# Implement steps by copying to a domain-specific file in tests/steps/.",
        "import pytest",
        "from pytest_bdd import given, when, then",
        "",
    ]

    for req_id, verb, text in steps:
        decorator = verb.lower() if verb.lower() in {"given", "when", "then"} else "then"
        func = step_to_func(verb, text)
        lines += [
            f"# {req_id}",
            f'@{decorator}("{text}")',
            f"def {func}():",
            f'    pytest.skip("step not implemented: {text[:60]}")',
            "",
        ]

    return "\n".join(lines)


def main() -> int:
    feature_files = list(FEATURES_DIR.glob("REQ-*.feature"))
    if not feature_files:
        print(f"No .feature files found in {FEATURES_DIR}/", file=sys.stderr)
        return 1

    STEPS_DIR.mkdir(parents=True, exist_ok=True)
    content = generate_stubs(feature_files)
    STUB_FILE.write_text(content)
    print(f"Written: {STUB_FILE} ({len(feature_files)} features processed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
