apiVersion: v2
name: provisa
description: Config-driven data virtualization platform
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: prometheus
    version: "25.x"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: observability.prometheus.enabled
  - name: grafana
    version: "7.x"
    repository: "https://grafana.github.io/helm-charts"
    condition: observability.grafana.enabled
