# Copyright (c) 2026 Kenneth Stott
# Canary: eebe02cb-7516-4c40-8cc9-7c54e03a4b12
#
# This source code is licensed under the Business Source License 1.1
# found in the LICENSE file in the root directory of this source tree.
#
# NOTICE: Use of this software for training artificial intelligence or
# machine learning models is strictly prohibited without explicit written
# permission from the copyright holder.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: approval.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'approval.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61pproval.proto\x12\x0cprovisa.auth\"b\n\x0f\x41pprovalRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\r\n\x05roles\x18\x02 \x03(\t\x12\x0e\n\x06tables\x18\x03 \x03(\t\x12\x0f\n\x07\x63olumns\x18\x04 \x03(\t\x12\x11\n\toperation\x18\x05 \x01(\t\"4\n\x10\x41pprovalResponse\x12\x10\n\x08\x61pproved\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2\\\n\x0f\x41pprovalService\x12I\n\x08\x45valuate\x12\x1d.provisa.auth.ApprovalRequest\x1a\x1e.provisa.auth.ApprovalResponseB \n\x10\x63om.provisa.authZ\x0cprovisa/authb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'approval_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.provisa.authZ\014provisa/auth'
  _globals['_APPROVALREQUEST']._serialized_start=32
  _globals['_APPROVALREQUEST']._serialized_end=130
  _globals['_APPROVALRESPONSE']._serialized_start=132
  _globals['_APPROVALRESPONSE']._serialized_end=184
  _globals['_APPROVALSERVICE']._serialized_start=186
  _globals['_APPROVALSERVICE']._serialized_end=278
# @@protoc_insertion_point(module_scope)
