# Copyright (c) 2026 Kenneth Stott
# Canary: c97b5f6d-4bed-48ce-82df-6793bf9eb325
#
# This source code is licensed under the Business Source License 1.1
# found in the LICENSE file in the root directory of this source tree.
#
# NOTICE: Use of this software for training artificial intelligence or
# machine learning models is strictly prohibited without explicit written
# permission from the copyright holder.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: approval.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'approval.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61pproval.proto\x12\x0cprovisa.auth\"\xdc\x01\n\x0f\x41pprovalRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\r\n\x05roles\x18\x02 \x03(\t\x12\x0e\n\x06tables\x18\x03 \x03(\t\x12\x0f\n\x07\x63olumns\x18\x04 \x03(\t\x12\x11\n\toperation\x18\x05 \x01(\t\x12\x44\n\x0csession_vars\x18\x06 \x03(\x0b\x32..provisa.auth.ApprovalRequest.SessionVarsEntry\x1a\x32\n\x10SessionVarsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"O\n\x10\x41pprovalResponse\x12\x10\n\x08\x61pproved\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x19\n\x11\x61\x64\x64itional_filter\x18\x03 \x01(\t2\\\n\x0f\x41pprovalService\x12I\n\x08\x45valuate\x12\x1d.provisa.auth.ApprovalRequest\x1a\x1e.provisa.auth.ApprovalResponseB \n\x10\x63om.provisa.authZ\x0cprovisa/authb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'approval_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.provisa.authZ\014provisa/auth'
  _globals['_APPROVALREQUEST_SESSIONVARSENTRY']._loaded_options = None
  _globals['_APPROVALREQUEST_SESSIONVARSENTRY']._serialized_options = b'8\001'
  _globals['_APPROVALREQUEST']._serialized_start=33
  _globals['_APPROVALREQUEST']._serialized_end=253
  _globals['_APPROVALREQUEST_SESSIONVARSENTRY']._serialized_start=203
  _globals['_APPROVALREQUEST_SESSIONVARSENTRY']._serialized_end=253
  _globals['_APPROVALRESPONSE']._serialized_start=255
  _globals['_APPROVALRESPONSE']._serialized_end=334
  _globals['_APPROVALSERVICE']._serialized_start=336
  _globals['_APPROVALSERVICE']._serialized_end=428
# @@protoc_insertion_point(module_scope)
