# Copyright (c) 2026 Kenneth Stott
# Canary: 0271927b-ec9a-4bac-a13d-bd8eea5607c0
#
# This source code is licensed under the Business Source License 1.1
# found in the LICENSE file in the root directory of this source tree.

"""Which config file this process runs on (REQ-528).

Every launcher sets ``PROVISA_CONFIG``: ``start-ui-install.sh`` exports it (the demo config or the
wizard skeleton), ``provisa/cli.py`` sets it for the embedded runtime, and the generated compose
files set it for a container. Nothing supplies ``config/provisa.yaml`` — the Dockerfile refuses to
bake that file (it is the divergent dev-local config) and no deploy pushes it — so reading it as a
default turned an unset variable into a ``FileNotFoundError`` raised deep inside Trino config
generation, several frames from the actual cause.
"""

import os
from pathlib import Path

_UNSET = (
    "PROVISA_CONFIG is not set. It names the config file this process loads, and every launcher "
    "sets it: start-ui-install.sh, provisa.cli for the embedded runtime, and the compose files "
    "generated by packaging/linux/first-launch.sh. A container started outside those paths has to "
    "set it explicitly."
)


def config_path() -> Path:
    """The config file this process loads."""
    value = os.environ.get("PROVISA_CONFIG")
    if not value:
        raise RuntimeError(_UNSET)
    return Path(value)


def config_path_str() -> str:
    """``config_path`` for the call sites that pass the path on as a string."""
    return str(config_path())
