connector.name=singlestore
connection-url=jdbc:singlestore://${ENV:SINGLESTORE_HOST}:${ENV:SINGLESTORE_PORT:-3306}
connection-user=${ENV:SINGLESTORE_USER}
connection-password=${ENV:SINGLESTORE_PASSWORD}
