connector.name=kafka
kafka.nodes=kafka:29092
kafka.table-description-supplier=FILE
kafka.table-description-dir=/etc/trino/kafka
kafka.table-names=support_tickets
kafka.hide-internal-columns=false
kafka.default-schema=default
